# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.halo] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_halo set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.slide2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_slide2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.ruby_gun] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ruby_gun set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.arm_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.arm_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.slide] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_slide set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.sapphire_gun] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sapphire_gun set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.shotgun] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_shotgun set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.rocket] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rocket set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.launcher] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_launcher set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.arm_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.arm_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.wing_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.wing_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.wing_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.wing_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.body_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.leg_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.leg_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.leg_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.leg_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.skirt_forward_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_forward_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.skirt_forward_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_forward_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.skirt_forward] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_forward set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.skirt_back_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_back_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.skirt_back_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_back_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.skirt_back] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.skirt_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.skirt_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.belt_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_belt_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.belt_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_belt_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.belt_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_belt_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.belt_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_belt_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_sapphiel.bone.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out