# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:haruclaire_aj/animations/1_0_rod_idle/zzz/apply_frame {frame: 50}
scoreboard players add @s aj.1_0_rod_idle.frame 1