# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.gem_attack_drone.node.head] {} merge from storage aj.gem_attack_drone:animations idle.$(frame).4
$execute on passengers run data modify entity @s[tag=aj.gem_attack_drone.node.weapon_model] {} merge from storage aj.gem_attack_drone:animations idle.$(frame).7
$execute on passengers run data modify entity @s[tag=aj.gem_attack_drone.node.arm_right] {} merge from storage aj.gem_attack_drone:animations idle.$(frame).5
$execute on passengers run data modify entity @s[tag=aj.gem_attack_drone.node.arm_left] {} merge from storage aj.gem_attack_drone:animations idle.$(frame).8
$execute on passengers run data modify entity @s[tag=aj.gem_attack_drone.node.body_1] {} merge from storage aj.gem_attack_drone:animations idle.$(frame).3
$execute on passengers run data modify entity @s[tag=aj.gem_attack_drone.node.leg] {} merge from storage aj.gem_attack_drone:animations idle.$(frame).9
$execute on passengers run data modify entity @s[tag=aj.gem_attack_drone.node.body_0] {} merge from storage aj.gem_attack_drone:animations idle.$(frame).2
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1