# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.lexiel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'lexiel', 'function_path': 'animated_java:lexiel/animations/attack1/stop'}
tag @s remove aj.lexiel.animation.attack1.playing
scoreboard players set @s aj.attack1.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:lexiel/animations/attack1/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only