# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.karmic.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'karmic', 'function_path': 'animated_java:karmic/animations/wait/resume'}
tag @s add aj.karmic.animation.wait.playing