# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.6_0_hg_punch.frame
function animated_java:twins_sapphiel/animations/6_0_hg_punch/zzz/apply_frame with storage aj:temp
execute if score @s aj.6_0_hg_punch.frame matches 76.. run return run function animated_java:twins_sapphiel/animations/6_0_hg_punch/pause
scoreboard players add @s aj.6_0_hg_punch.frame 1