# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data merge entity @s {Silent:1b,NoAI:1b,Size:3,Health:2048f,DeathLootTable:"minecraft:empty",ArmorItems:[{},{},{},{id:"minecraft:blaze_rod",Count:1b,tag:{CustomModelData:1,AttributeModifiers:[{AttributeName:"generic.max_health",Name:"generic.max_health",Amount:1024,Operation:0,UUID:[I;-968890433,-1598797109,-1709380017,697125493]}]}}]}