# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.frestchika.root] run return 0
execute on passengers if entity @s[tag=aj.frestchika.data] unless data entity @s {data:{rigHash: '3c715040d246c87be3927af646fcb4688650040be5e9e088f02756c9cfbb135d'}} on vehicle run function animated_java:frestchika/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1