# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.gem_panjan_drone.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gem_panjan_drone', 'function_path': 'animated_java:gem_panjan_drone/animations/move_start/next_frame'}
execute if score @s aj.move_start.frame matches 21.. run scoreboard players set @s aj.move_start.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.move_start.frame
execute at @s run function animated_java:gem_panjan_drone/animations/move_start/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.move_start.frame 1