# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:behemoth_aj/animations/10_1_blazing_cast/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.10_1_blazing_cast.frame 1