# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gem_panjan_drone.root] run return 0
execute on passengers if entity @s[tag=aj.gem_panjan_drone.data] unless data entity @s {data:{rigHash: 'ab9c3b2b46ab44add91a0e0bb9ee353d484d3efe78fca764bafb0a8eb28a185c'}} on vehicle run function animated_java:gem_panjan_drone/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1