# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.karmic.node.head] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).2
$execute on passengers if entity @s[tag=aj.karmic.node.rightscythe_handle] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).6
$execute on passengers if entity @s[tag=aj.karmic.node.sword] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).7
$execute on passengers if entity @s[tag=aj.karmic.node.righthand] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).4
$execute on passengers if entity @s[tag=aj.karmic.node.rightarm] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).3
$execute on passengers if entity @s[tag=aj.karmic.node.gun] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).a
$execute on passengers if entity @s[tag=aj.karmic.node.leftscythe_handle] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).c
$execute on passengers if entity @s[tag=aj.karmic.node.lefthand] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).9
$execute on passengers if entity @s[tag=aj.karmic.node.leftarm] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).8
$execute on passengers if entity @s[tag=aj.karmic.node.body] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).1
$execute on passengers if entity @s[tag=aj.karmic.node.leftfeet] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).f
$execute on passengers if entity @s[tag=aj.karmic.node.leftleg] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).e
$execute on passengers if entity @s[tag=aj.karmic.node.rightfeet] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).h
$execute on passengers if entity @s[tag=aj.karmic.node.rightleg] run data modify entity @s {} merge from storage aj.karmic:animations sword_change.$(frame).g