# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:heiloang_aj/remove/zzz/kill with entity @s data.locators.hitbox_head_0
function animated_java:heiloang_aj/remove/zzz/kill with entity @s data.locators.hitbox_head_1
function animated_java:heiloang_aj/remove/zzz/kill with entity @s data.locators.hitbox_head_2
function animated_java:heiloang_aj/remove/zzz/kill with entity @s data.locators.hitbox_head_3
function animated_java:heiloang_aj/remove/zzz/kill with entity @s data.locators.hitbox_head_7
function animated_java:heiloang_aj/remove/zzz/kill with entity @s data.locators.hitbox_head_6
function animated_java:heiloang_aj/remove/zzz/kill with entity @s data.locators.hitbox_head_5
function animated_java:heiloang_aj/remove/zzz/kill with entity @s data.locators.hitbox_head_4