# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tutankhamen/animations/attack_dash_2/zzz/apply_frame {frame: 5}
scoreboard players add @s aj.attack_dash_2.frame 1