# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ic_capri_aj.root] run return 0
execute on passengers if entity @s[tag=aj.ic_capri_aj.data] unless data entity @s {data:{rigHash: '05ee00d47f79ee959d13d2f1064912df2d4be9394cef2bc92d6c32409c534032'}} on vehicle run function animated_java:ic_capri_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1