# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.red_knight.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'red_knight', 'function_path': 'animated_java:red_knight/animations/neutral_ground/stop'}
tag @s remove aj.red_knight.animation.neutral_ground.playing
scoreboard players set @s aj.neutral_ground.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:red_knight/animations/neutral_ground/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only