# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.blazing_inferno.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'blazing_inferno', 'function_path': 'animated_java:blazing_inferno/animations/teleport_vanish/play'}
tag @s add aj.blazing_inferno.animation.teleport_vanish.playing
scoreboard players set @s aj.teleport_vanish.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:blazing_inferno/animations/teleport_vanish/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only