# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.sharkboss.root] run return 0
execute on passengers if entity @s[tag=aj.sharkboss.data] unless data entity @s {data:{rigHash: '72d6ee3d534fd2d8dc9e0c7ee05994044fa4484fb9493d9750def8478b224528'}} on vehicle run function animated_java:sharkboss/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1