# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.sharkboss.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:sharkboss/as_root/pre_tick
execute if entity @s[tag=aj.sharkboss.animation.gengeral.playing] run function animated_java:sharkboss/animations/gengeral/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.move_loop.playing] run function animated_java:sharkboss/animations/move_loop/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.tail.playing] run function animated_java:sharkboss/animations/tail/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.tail_strong.playing] run function animated_java:sharkboss/animations/tail_strong/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.bite_tail.playing] run function animated_java:sharkboss/animations/bite_tail/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.watergun.playing] run function animated_java:sharkboss/animations/watergun/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.tornado.playing] run function animated_java:sharkboss/animations/tornado/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.tornado_strong.playing] run function animated_java:sharkboss/animations/tornado_strong/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.emp.playing] run function animated_java:sharkboss/animations/emp/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.rush_start.playing] run function animated_java:sharkboss/animations/rush_start/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.rush_loop.playing] run function animated_java:sharkboss/animations/rush_loop/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.rush_end.playing] run function animated_java:sharkboss/animations/rush_end/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.rush_strong.playing] run function animated_java:sharkboss/animations/rush_strong/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.rush_end2.playing] run function animated_java:sharkboss/animations/rush_end2/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.puffer_start.playing] run function animated_java:sharkboss/animations/puffer_start/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.puffer_end.playing] run function animated_java:sharkboss/animations/puffer_end/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.down_start.playing] run function animated_java:sharkboss/animations/down_start/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.down_end.playing] run function animated_java:sharkboss/animations/down_end/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.down_loop.playing] run function animated_java:sharkboss/animations/down_loop/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.summon.playing] run function animated_java:sharkboss/animations/summon/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.death.playing] run function animated_java:sharkboss/animations/death/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.sharknado_start.playing] run function animated_java:sharkboss/animations/sharknado_start/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.sharknado_loop.playing] run function animated_java:sharkboss/animations/sharknado_loop/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.sharknado_slash.playing] run function animated_java:sharkboss/animations/sharknado_slash/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.sharknado_watergun.playing] run function animated_java:sharkboss/animations/sharknado_watergun/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.sharknado_end.playing] run function animated_java:sharkboss/animations/sharknado_end/zzz/on_tick
execute if entity @s[tag=aj.sharkboss.animation.bite.playing] run function animated_java:sharkboss/animations/bite/zzz/on_tick
execute on passengers if entity @s[tag=aj.sharkboss.data] run function animated_java:sharkboss/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:sharkboss/as_root/post_tick