# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.head] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_head
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.sword] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_sword
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.axe] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_axe
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.left_arm_2] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_left_arm_2
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.left_arm] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_left_arm
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.left_shoulder] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_left_shoulder
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.right_arm_2] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_right_arm_2
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.right_arm] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_right_arm
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.right_shoulder] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_right_shoulder
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.upper_body] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_upper_body
$execute on passengers run data modify entity @s[tag=aj.grey_guardian.bone.body] {} merge from storage aj.grey_guardian:animations attack5.$(frame).bone_body
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1