# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tiamat_aj/animations/3_8_casting_breath/zzz/apply_frame {frame: 34}
scoreboard players add @s aj.3_8_casting_breath.frame 1