# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.radar1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_radar1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.missile5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_missile5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.arm1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.turret3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_turret3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels11] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels12] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels12 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels13] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels13 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels14] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels14 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels15] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.wheels7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheels7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.ritai_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ritai_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.missile2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_missile2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.lid1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lid1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.patriot_launcher.node.root1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_root1 set from storage aj:uuid main.out