# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.haruclaire_aj.root] run return 0
execute on passengers if entity @s[tag=aj.haruclaire_aj.data] unless data entity @s {data:{rigHash: '30f910b1e1fa579feea50b7739c68dc09390a2e7b0c10ce5b7c09551fd641ef9'}} on vehicle run function animated_java:haruclaire_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1