# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.haruclaire_aj.root] run return 0
execute on passengers if entity @s[tag=aj.haruclaire_aj.data] unless data entity @s {data:{rigHash: '7eb3e068c724c8cfae3d9fd73b4e57d85b6c7f11812e104745bff307236bb43c'}} on vehicle run function animated_java:haruclaire_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1