# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gem_attack_drone.root] run return 0
execute on passengers if entity @s[tag=aj.gem_attack_drone.data] unless data entity @s {data:{rigHash: 'b6242868caca63f3aa0e613cb9da8830c9e1f6d4055bef524e4b48656cecfdce'}} on vehicle run function animated_java:gem_attack_drone/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1