# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lawless_iron_doll.root] run return 0
execute on passengers if entity @s[tag=aj.lawless_iron_doll.data] unless data entity @s {data:{rigHash: '40480d291e5f1e772ae23f14d442fc6b0e6d508dd348e28aa38223490a6c7344'}} on vehicle run function animated_java:lawless_iron_doll/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1