# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.ic_capri_aj.node.head3] run data modify entity @s {} merge from storage aj.ic_capri_aj:animations 2_attack.$(frame).bone_head3
$execute on passengers if entity @s[tag=aj.ic_capri_aj.node.arm_right2] run data modify entity @s {} merge from storage aj.ic_capri_aj:animations 2_attack.$(frame).bone_arm_right2
$execute on passengers if entity @s[tag=aj.ic_capri_aj.node.arm_left2] run data modify entity @s {} merge from storage aj.ic_capri_aj:animations 2_attack.$(frame).bone_arm_left2
$execute on passengers if entity @s[tag=aj.ic_capri_aj.node.body5] run data modify entity @s {} merge from storage aj.ic_capri_aj:animations 2_attack.$(frame).bone_body5
$execute on passengers if entity @s[tag=aj.ic_capri_aj.node.leg_left2] run data modify entity @s {} merge from storage aj.ic_capri_aj:animations 2_attack.$(frame).bone_leg_left2
$execute on passengers if entity @s[tag=aj.ic_capri_aj.node.leg_right2] run data modify entity @s {} merge from storage aj.ic_capri_aj:animations 2_attack.$(frame).bone_leg_right2
$execute on passengers if entity @s[tag=aj.ic_capri_aj.node.root3] run data modify entity @s {} merge from storage aj.ic_capri_aj:animations 2_attack.$(frame).bone_root3