# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.convict.bone.left_leg_2] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_left_leg_2
$execute on passengers if entity @s[tag=aj.convict.bone.left_leg] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_left_leg
$execute on passengers if entity @s[tag=aj.convict.bone.right_leg_2] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_right_leg_2
$execute on passengers if entity @s[tag=aj.convict.bone.right_leg] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_right_leg
$execute on passengers if entity @s[tag=aj.convict.bone.head] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_head
$execute on passengers if entity @s[tag=aj.convict.bone.left_axe] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_left_axe
$execute on passengers if entity @s[tag=aj.convict.bone.left_arm_2] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_left_arm_2
$execute on passengers if entity @s[tag=aj.convict.bone.left_arm] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_left_arm
$execute on passengers if entity @s[tag=aj.convict.bone.right_axe] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_right_axe
$execute on passengers if entity @s[tag=aj.convict.bone.right_arm_2] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_right_arm_2
$execute on passengers if entity @s[tag=aj.convict.bone.right_arm] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_right_arm
$execute on passengers if entity @s[tag=aj.convict.bone.body] run data modify entity @s {} merge from storage aj.convict:animations attack7.$(frame).bone_body