# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.eclael.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'eclael', 'function_path': 'animated_java:eclael/animations/13_4_latter_quick_move/play'}
tag @s add aj.eclael.animation.13_4_latter_quick_move.playing
scoreboard players set @s aj.13_4_latter_quick_move.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:eclael/animations/13_4_latter_quick_move/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only