# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.attack_magic_1_right.frame $(frame)
execute at @s run function animated_java:illusion_of_loyalty/animations/attack_magic_1_right/zzz/apply_frame with storage aj:temp