# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.tiamat_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'tiamat_aj', 'function_path': 'animated_java:tiamat_aj/animations/1_idle2/play'}
tag @s add aj.tiamat_aj.animation.1_idle2.playing
scoreboard players set @s aj.1_idle2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:tiamat_aj/animations/1_idle2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only