# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.louvert.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'louvert', 'function_path': 'animated_java:louvert/animations/03_2_fire_slash_slash_1/stop'}
tag @s remove aj.louvert.animation.03_2_fire_slash_slash_1.playing
scoreboard players set @s aj.03_2_fire_slash_slash_1.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:louvert/animations/03_2_fire_slash_slash_1/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only