# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:behemoth_aj/animations/3_5_casting_flatten/zzz/apply_frame {frame: 45}
scoreboard players add @s aj.3_5_casting_flatten.frame 1