# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.haruclaire_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'haruclaire_aj', 'function_path': 'animated_java:haruclaire_aj/animations/23_1_second_twin_laser_shooting/play'}
tag @s add aj.haruclaire_aj.animation.23_1_second_twin_laser_shooting.playing
scoreboard players set @s aj.23_1_second_twin_laser_shooting.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:haruclaire_aj/animations/23_1_second_twin_laser_shooting/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only