# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.patriot_launcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'patriot_launcher', 'function_path': 'animated_java:patriot_launcher/animations/destroy/next_frame'}
execute if score @s aj.destroy.frame matches 2.. run scoreboard players set @s aj.destroy.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.destroy.frame
execute at @s run function animated_java:patriot_launcher/animations/destroy/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.destroy.frame 1