# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.head3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_head3
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.arm_right_3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_arm_right_3
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.arm_right_2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_arm_right_2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.arm_left_3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_arm_left_3
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.arm_left_2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_arm_left_2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.body_3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_body_3
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.leg_right2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_leg_right2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.leg_left2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_leg_left2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.tail2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_tail2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.body_4] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).bone_body_4