# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.head3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).4
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.arm_right_3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).6
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.arm_right_2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).5
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.arm_left_3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).8
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.arm_left_2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).7
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.body_3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).3
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.leg_right2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).9
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.leg_left2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).a
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.tail2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).b
$execute on passengers if entity @s[tag=aj.ic_tau_aj.node.body_4] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations pose.$(frame).2