# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:grey_guardian/animations/tacle_start/zzz/apply_frame {frame: 48}
scoreboard players add @s aj.tacle_start.frame 1