# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.frestchika.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:frestchika/as_root/pre_tick
execute if entity @s[tag=aj.frestchika.animation.intro.playing] run function animated_java:frestchika/animations/intro/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.neutral.playing] run function animated_java:frestchika/animations/neutral/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.dash_start.playing] run function animated_java:frestchika/animations/dash_start/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.dash_left.playing] run function animated_java:frestchika/animations/dash_left/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.dash_right.playing] run function animated_java:frestchika/animations/dash_right/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.dash_right_gun.playing] run function animated_java:frestchika/animations/dash_right_gun/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.dash_left_gun.playing] run function animated_java:frestchika/animations/dash_left_gun/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.dash_windup.playing] run function animated_java:frestchika/animations/dash_windup/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_slash_1_windup.playing] run function animated_java:frestchika/animations/attack_slash_1_windup/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_slash_1_active.playing] run function animated_java:frestchika/animations/attack_slash_1_active/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_2_right.playing] run function animated_java:frestchika/animations/attack_2_right/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_2_left.playing] run function animated_java:frestchika/animations/attack_2_left/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_slash_2_windup.playing] run function animated_java:frestchika/animations/attack_slash_2_windup/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_slash_2_active.playing] run function animated_java:frestchika/animations/attack_slash_2_active/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_slash_3.playing] run function animated_java:frestchika/animations/attack_slash_3/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_slash_4_windup.playing] run function animated_java:frestchika/animations/attack_slash_4_windup/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_slash_4_active.playing] run function animated_java:frestchika/animations/attack_slash_4_active/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_slash_5_windup.playing] run function animated_java:frestchika/animations/attack_slash_5_windup/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_slash_5_active.playing] run function animated_java:frestchika/animations/attack_slash_5_active/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.attack_ranged_1.playing] run function animated_java:frestchika/animations/attack_ranged_1/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.break.playing] run function animated_java:frestchika/animations/break/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.break_loop.playing] run function animated_java:frestchika/animations/break_loop/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.recovery.playing] run function animated_java:frestchika/animations/recovery/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.teleport.playing] run function animated_java:frestchika/animations/teleport/zzz/on_tick
execute if entity @s[tag=aj.frestchika.animation.death.playing] run function animated_java:frestchika/animations/death/zzz/on_tick
execute on passengers if entity @s[tag=aj.frestchika.data] run function animated_java:frestchika/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:frestchika/as_root/post_tick