# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.blazing_inferno.bone.body] {} merge from storage aj.blazing_inferno:animations posing.$(frame).bone_body
$execute on passengers run data modify entity @s[tag=aj.blazing_inferno.bone.left_hand] {} merge from storage aj.blazing_inferno:animations posing.$(frame).bone_left_hand
$execute on passengers run data modify entity @s[tag=aj.blazing_inferno.bone.left_arm] {} merge from storage aj.blazing_inferno:animations posing.$(frame).bone_left_arm
$execute on passengers run data modify entity @s[tag=aj.blazing_inferno.bone.right_hand] {} merge from storage aj.blazing_inferno:animations posing.$(frame).bone_right_hand
$execute on passengers run data modify entity @s[tag=aj.blazing_inferno.bone.right_arm] {} merge from storage aj.blazing_inferno:animations posing.$(frame).bone_right_arm
$execute on passengers run data modify entity @s[tag=aj.blazing_inferno.bone.head] {} merge from storage aj.blazing_inferno:animations posing.$(frame).bone_head
$execute on passengers run data modify entity @s[tag=aj.blazing_inferno.bone.bottom] {} merge from storage aj.blazing_inferno:animations posing.$(frame).bone_bottom
$execute on passengers if entity @s[tag=aj.data] run data modify entity @s data.locators.locator_left_hand merge from storage aj.blazing_inferno:animations posing.$(frame).locator_locator_left_hand
$execute on passengers if entity @s[tag=aj.data] run data modify entity @s data.locators.locator_right_hand merge from storage aj.blazing_inferno:animations posing.$(frame).locator_locator_right_hand
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1