# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gargo_ex_machina.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:gargo_ex_machina/as_root/pre_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.pose.playing] run function animated_java:gargo_ex_machina/animations/pose/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.activation.playing] run function animated_java:gargo_ex_machina/animations/activation/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.move_to_field_slow.playing] run function animated_java:gargo_ex_machina/animations/move_to_field_slow/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.move_to_field_fast.playing] run function animated_java:gargo_ex_machina/animations/move_to_field_fast/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.move_to_field_short.playing] run function animated_java:gargo_ex_machina/animations/move_to_field_short/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.change_head_start.playing] run function animated_java:gargo_ex_machina/animations/change_head_start/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.change_head.playing] run function animated_java:gargo_ex_machina/animations/change_head/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.death.playing] run function animated_java:gargo_ex_machina/animations/death/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.idle.playing] run function animated_java:gargo_ex_machina/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.idle_shot.playing] run function animated_java:gargo_ex_machina/animations/idle_shot/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.walk_start.playing] run function animated_java:gargo_ex_machina/animations/walk_start/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.walk.playing] run function animated_java:gargo_ex_machina/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.walk_end.playing] run function animated_java:gargo_ex_machina/animations/walk_end/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.walk_bak.playing] run function animated_java:gargo_ex_machina/animations/walk_bak/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.change_to_shot.playing] run function animated_java:gargo_ex_machina/animations/change_to_shot/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.change_to_sword.playing] run function animated_java:gargo_ex_machina/animations/change_to_sword/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.sword_smash_start.playing] run function animated_java:gargo_ex_machina/animations/sword_smash_start/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.sword_smash_charge.playing] run function animated_java:gargo_ex_machina/animations/sword_smash_charge/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.sword_smash_attack.playing] run function animated_java:gargo_ex_machina/animations/sword_smash_attack/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.sword_smash_attack_double.playing] run function animated_java:gargo_ex_machina/animations/sword_smash_attack_double/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_start.playing] run function animated_java:gargo_ex_machina/animations/beam_start/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_charge.playing] run function animated_java:gargo_ex_machina/animations/beam_charge/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_attack_right.playing] run function animated_java:gargo_ex_machina/animations/beam_attack_right/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_attack_left.playing] run function animated_java:gargo_ex_machina/animations/beam_attack_left/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_end.playing] run function animated_java:gargo_ex_machina/animations/beam_end/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_sword_start.playing] run function animated_java:gargo_ex_machina/animations/beam_sword_start/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_sword_charge.playing] run function animated_java:gargo_ex_machina/animations/beam_sword_charge/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_sword_attack_right.playing] run function animated_java:gargo_ex_machina/animations/beam_sword_attack_right/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_sword_attack_left.playing] run function animated_java:gargo_ex_machina/animations/beam_sword_attack_left/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_shot_start.playing] run function animated_java:gargo_ex_machina/animations/beam_shot_start/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_shot_charge.playing] run function animated_java:gargo_ex_machina/animations/beam_shot_charge/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_shot_attack_right.playing] run function animated_java:gargo_ex_machina/animations/beam_shot_attack_right/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.beam_shot_attack_left.playing] run function animated_java:gargo_ex_machina/animations/beam_shot_attack_left/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.super_jump_start.playing] run function animated_java:gargo_ex_machina/animations/super_jump_start/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.super_jump_end.playing] run function animated_java:gargo_ex_machina/animations/super_jump_end/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.shot_target.playing] run function animated_java:gargo_ex_machina/animations/shot_target/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.shot_target_spin.playing] run function animated_java:gargo_ex_machina/animations/shot_target_spin/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.shot_upper.playing] run function animated_java:gargo_ex_machina/animations/shot_upper/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.summon_punch.playing] run function animated_java:gargo_ex_machina/animations/summon_punch/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.call_drone.playing] run function animated_java:gargo_ex_machina/animations/call_drone/zzz/on_tick
execute if entity @s[tag=aj.gargo_ex_machina.animation.call_drone_first.playing] run function animated_java:gargo_ex_machina/animations/call_drone_first/zzz/on_tick
execute on passengers if entity @s[tag=aj.gargo_ex_machina.data] run function animated_java:gargo_ex_machina/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:gargo_ex_machina/as_root/post_tick