# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.gem_panjan_drone.node.arm] {} merge from storage aj.gem_panjan_drone:animations idle.$(frame).4
$execute on passengers run data modify entity @s[tag=aj.gem_panjan_drone.node.body] {} merge from storage aj.gem_panjan_drone:animations idle.$(frame).3
$execute on passengers run data modify entity @s[tag=aj.gem_panjan_drone.node.machine] {} merge from storage aj.gem_panjan_drone:animations idle.$(frame).2
$execute on passengers run data modify entity @s[tag=aj.gem_panjan_drone.node.blade_right] {} merge from storage aj.gem_panjan_drone:animations idle.$(frame).6
$execute on passengers run data modify entity @s[tag=aj.gem_panjan_drone.node.hellblade_right] {} merge from storage aj.gem_panjan_drone:animations idle.$(frame).5
$execute on passengers run data modify entity @s[tag=aj.gem_panjan_drone.node.blade_left] {} merge from storage aj.gem_panjan_drone:animations idle.$(frame).8
$execute on passengers run data modify entity @s[tag=aj.gem_panjan_drone.node.hellblade_left] {} merge from storage aj.gem_panjan_drone:animations idle.$(frame).7
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1