# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tiamat_aj/animations/2_move/zzz/apply_frame {frame: 50}
scoreboard players add @s aj.2_move.frame 1