# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.red_knight.bone.head] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_head
$execute on passengers if entity @s[tag=aj.red_knight.bone.body] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_body
$execute on passengers if entity @s[tag=aj.red_knight.bone.left_hand] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_left_hand
$execute on passengers if entity @s[tag=aj.red_knight.bone.left_arm] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_left_arm
$execute on passengers if entity @s[tag=aj.red_knight.bone.weapon] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_weapon
$execute on passengers if entity @s[tag=aj.red_knight.bone.right_hand] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_right_hand
$execute on passengers if entity @s[tag=aj.red_knight.bone.right_arm] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_right_arm
$execute on passengers if entity @s[tag=aj.red_knight.bone.waist] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_waist
$execute on passengers if entity @s[tag=aj.red_knight.bone.left_foot] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_left_foot
$execute on passengers if entity @s[tag=aj.red_knight.bone.left_leg] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_left_leg
$execute on passengers if entity @s[tag=aj.red_knight.bone.right_foot] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_right_foot
$execute on passengers if entity @s[tag=aj.red_knight.bone.right_leg] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_right_leg
$execute on passengers if entity @s[tag=aj.red_knight.bone.weapon_ground] run data modify entity @s {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_weapon_ground