# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.lawless_iron_doll.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'lawless_iron_doll', 'function_path': 'animated_java:lawless_iron_doll/animations/pause_all'}
tag @s remove aj.lawless_iron_doll.animation.intro.playing
tag @s remove aj.lawless_iron_doll.animation.neutral.playing
tag @s remove aj.lawless_iron_doll.animation.attack_melee_1_windup.playing
tag @s remove aj.lawless_iron_doll.animation.attack_melee_1_activate.playing
tag @s remove aj.lawless_iron_doll.animation.attack_melee_2_windup.playing
tag @s remove aj.lawless_iron_doll.animation.attack_melee_2_activate.playing
tag @s remove aj.lawless_iron_doll.animation.attack_melee_3_windup.playing
tag @s remove aj.lawless_iron_doll.animation.attack_melee_3_activate.playing
tag @s remove aj.lawless_iron_doll.animation.attack_slam.playing
tag @s remove aj.lawless_iron_doll.animation.attack_ranged_1_windup.playing
tag @s remove aj.lawless_iron_doll.animation.attack_ranged_1_activate.playing
tag @s remove aj.lawless_iron_doll.animation.attack_ranged_2_windup.playing
tag @s remove aj.lawless_iron_doll.animation.attack_ranged_2_activate.playing
tag @s remove aj.lawless_iron_doll.animation.attack_ranged_2_loop.playing
tag @s remove aj.lawless_iron_doll.animation.break.playing
tag @s remove aj.lawless_iron_doll.animation.recovery.playing
tag @s remove aj.lawless_iron_doll.animation.death.playing
tag @s remove aj.lawless_iron_doll.animation.jump.playing
tag @s remove aj.lawless_iron_doll.animation.walk.playing
tag @s remove aj.lawless_iron_doll.animation.run.playing
tag @s remove aj.lawless_iron_doll.animation.run2.playing
tag @s remove aj.lawless_iron_doll.animation.run2_stop.playing