# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.twins_sapphiel.root] run return 0
execute on passengers if entity @s[tag=aj.twins_sapphiel.data] unless data entity @s {data:{rigHash: 'c461c5aa80d8484de721d3da212b8e944aff141a134395585bd699f3931bf4c9'}} on vehicle run function animated_java:twins_sapphiel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1