# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.twins_sapphiel.root] run return 0
execute on passengers if entity @s[tag=aj.twins_sapphiel.data] unless data entity @s {data:{rigHash: 'a784a39254dfc90bdfc9236f625a3e8f317938165cc2c29e1e95ea95a4043ecc'}} on vehicle run function animated_java:twins_sapphiel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1