# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.test.bone.block_display] {} merge from storage aj.test:animations animation_model_new.$(frame).block_display_block_display
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1