# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.convict.node.left_leg_2] {} merge from storage aj.convict:animations summon.$(frame).2
$execute on passengers run data modify entity @s[tag=aj.convict.node.left_leg] {} merge from storage aj.convict:animations summon.$(frame).1
$execute on passengers run data modify entity @s[tag=aj.convict.node.right_leg_2] {} merge from storage aj.convict:animations summon.$(frame).4
$execute on passengers run data modify entity @s[tag=aj.convict.node.right_leg] {} merge from storage aj.convict:animations summon.$(frame).3
$execute on passengers run data modify entity @s[tag=aj.convict.node.head] {} merge from storage aj.convict:animations summon.$(frame).6
$execute on passengers run data modify entity @s[tag=aj.convict.node.left_axe] {} merge from storage aj.convict:animations summon.$(frame).9
$execute on passengers run data modify entity @s[tag=aj.convict.node.left_arm_2] {} merge from storage aj.convict:animations summon.$(frame).8
$execute on passengers run data modify entity @s[tag=aj.convict.node.left_arm] {} merge from storage aj.convict:animations summon.$(frame).7
$execute on passengers run data modify entity @s[tag=aj.convict.node.right_axe] {} merge from storage aj.convict:animations summon.$(frame).c
$execute on passengers run data modify entity @s[tag=aj.convict.node.right_arm_2] {} merge from storage aj.convict:animations summon.$(frame).b
$execute on passengers run data modify entity @s[tag=aj.convict.node.right_arm] {} merge from storage aj.convict:animations summon.$(frame).a
$execute on passengers run data modify entity @s[tag=aj.convict.node.body] {} merge from storage aj.convict:animations summon.$(frame).5
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1