# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.eclael.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'eclael', 'function_path': 'animated_java:eclael/animations/20_1_latter_attack_shot_1/next_frame'}
execute if score @s aj.20_1_latter_attack_shot_1.frame matches 41.. run scoreboard players set @s aj.20_1_latter_attack_shot_1.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.20_1_latter_attack_shot_1.frame
execute at @s run function animated_java:eclael/animations/20_1_latter_attack_shot_1/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.20_1_latter_attack_shot_1.frame 1