# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.heiloang_aj.root] run return 0
execute on passengers if entity @s[tag=aj.heiloang_aj.data] unless data entity @s {data:{rigHash: 'fd372dadd526a6ed2c5ab02e96a53f53f73c0a36ca1f910fb6b06c77ded59f76'}} on vehicle run function animated_java:heiloang_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1