# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.heiloang_aj.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:heiloang_aj/as_root/pre_tick
execute if entity @s[tag=aj.heiloang_aj.animation.000_pose.playing] run function animated_java:heiloang_aj/animations/000_pose/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.1_idle.playing] run function animated_java:heiloang_aj/animations/1_idle/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.2_0_common_cast_start.playing] run function animated_java:heiloang_aj/animations/2_0_common_cast_start/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.2_1_common_casting.playing] run function animated_java:heiloang_aj/animations/2_1_common_casting/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.2_2_common_invoke.playing] run function animated_java:heiloang_aj/animations/2_2_common_invoke/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.2_3_common_order.playing] run function animated_java:heiloang_aj/animations/2_3_common_order/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.3_0_hellfire_start.playing] run function animated_java:heiloang_aj/animations/3_0_hellfire_start/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.3_1_hellfire_shoot.playing] run function animated_java:heiloang_aj/animations/3_1_hellfire_shoot/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.3_2_hellfire_shoot_end.playing] run function animated_java:heiloang_aj/animations/3_2_hellfire_shoot_end/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.4_blizzard.playing] run function animated_java:heiloang_aj/animations/4_blizzard/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.5_1_move_start.playing] run function animated_java:heiloang_aj/animations/5_1_move_start/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.5_2_move.playing] run function animated_java:heiloang_aj/animations/5_2_move/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.6_sweep_breath.playing] run function animated_java:heiloang_aj/animations/6_sweep_breath/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.6_1_sweep_breath_mirror.playing] run function animated_java:heiloang_aj/animations/6_1_sweep_breath_mirror/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.7_1_dive_start.playing] run function animated_java:heiloang_aj/animations/7_1_dive_start/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.7_2_dive.playing] run function animated_java:heiloang_aj/animations/7_2_dive/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.7_3_dive_end.playing] run function animated_java:heiloang_aj/animations/7_3_dive_end/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.8_1_move_flare.playing] run function animated_java:heiloang_aj/animations/8_1_move_flare/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.9_1_plamet.playing] run function animated_java:heiloang_aj/animations/9_1_plamet/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.9_2_plamet_dive.playing] run function animated_java:heiloang_aj/animations/9_2_plamet_dive/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.10_1_power_breath.playing] run function animated_java:heiloang_aj/animations/10_1_power_breath/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.10_2_power_breath_continue_1.playing] run function animated_java:heiloang_aj/animations/10_2_power_breath_continue_1/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.10_3_power_breath_continue_2.playing] run function animated_java:heiloang_aj/animations/10_3_power_breath_continue_2/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.10_4_power_breath_continue_end.playing] run function animated_java:heiloang_aj/animations/10_4_power_breath_continue_end/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.11_damage.playing] run function animated_java:heiloang_aj/animations/11_damage/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.12_0_flymove_start.playing] run function animated_java:heiloang_aj/animations/12_0_flymove_start/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.12_1_flymove_end.playing] run function animated_java:heiloang_aj/animations/12_1_flymove_end/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.13_summon.playing] run function animated_java:heiloang_aj/animations/13_summon/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.14_awaken.playing] run function animated_java:heiloang_aj/animations/14_awaken/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.15_death.playing] run function animated_java:heiloang_aj/animations/15_death/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.16_final_flare.playing] run function animated_java:heiloang_aj/animations/16_final_flare/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.99_disaster_cast.playing] run function animated_java:heiloang_aj/animations/99_disaster_cast/zzz/on_tick
execute if entity @s[tag=aj.heiloang_aj.animation.99_disaster.playing] run function animated_java:heiloang_aj/animations/99_disaster/zzz/on_tick
execute on passengers if entity @s[tag=aj.heiloang_aj.data] run function animated_java:heiloang_aj/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:heiloang_aj/as_root/post_tick