# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.tutankhamen.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'tutankhamen', 'function_path': 'animated_java:tutankhamen/animations/pause_all'}
tag @s remove aj.tutankhamen.animation.beam_wait.playing
tag @s remove aj.tutankhamen.animation.beam_shot.playing
tag @s remove aj.tutankhamen.animation.beam_end.playing
tag @s remove aj.tutankhamen.animation.neutral.playing
tag @s remove aj.tutankhamen.animation.dash.playing
tag @s remove aj.tutankhamen.animation.dash_end.playing
tag @s remove aj.tutankhamen.animation.attack_magic_1.playing
tag @s remove aj.tutankhamen.animation.attack_magic_2.playing
tag @s remove aj.tutankhamen.animation.beam_start.playing
tag @s remove aj.tutankhamen.animation.spawn.playing
tag @s remove aj.tutankhamen.animation.soul_shot.playing
tag @s remove aj.tutankhamen.animation.beam_long_shot.playing
tag @s remove aj.tutankhamen.animation.beam_long_charge.playing
tag @s remove aj.tutankhamen.animation.beam_long.playing
tag @s remove aj.tutankhamen.animation.dash_slash.playing
tag @s remove aj.tutankhamen.animation.rod_ground_end.playing
tag @s remove aj.tutankhamen.animation.rod_ground.playing
tag @s remove aj.tutankhamen.animation.attack_melee_1.playing
tag @s remove aj.tutankhamen.animation.attack_dash_1.playing
tag @s remove aj.tutankhamen.animation.attack_dash_2.playing
tag @s remove aj.tutankhamen.animation.death_tokumei.playing
tag @s remove aj.tutankhamen.animation.death.playing