# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.eclael.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'eclael', 'function_path': 'animated_java:eclael/animations/4_3_former_upper_damage/next_frame'}
execute if score @s aj.4_3_former_upper_damage.frame matches 81.. run scoreboard players set @s aj.4_3_former_upper_damage.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.4_3_former_upper_damage.frame
execute at @s run function animated_java:eclael/animations/4_3_former_upper_damage/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.4_3_former_upper_damage.frame 1