# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blazing_inferno.root] run return 0
execute on passengers if entity @s[tag=aj.blazing_inferno.data] unless data entity @s {data:{rigHash: '20ed88a2426cacab14a996841af415aff19476dcf23609f18c69fb6516ab1c79'}} on vehicle run function animated_java:blazing_inferno/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1