# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blazing_inferno.root] run return 0
execute on passengers if entity @s[tag=aj.blazing_inferno.data] unless data entity @s {data:{rigHash: '9455f1d8875f667940a2225ee64f8b11914317600bfc0041030da5d32135b8cf'}} on vehicle run function animated_java:blazing_inferno/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1