# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blazing_inferno.root] run return 0
execute on passengers if entity @s[tag=aj.blazing_inferno.data] unless data entity @s {data:{rigHash: '370d77e65579fa4bba7aab462ca09b61d533d4e7c6dbe10a053e83d87376f4b4'}} on vehicle run function animated_java:blazing_inferno/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1