# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.terrible_sonic_bomber.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'terrible_sonic_bomber', 'function_path': 'animated_java:terrible_sonic_bomber/animations/roll_straight_and_wing_back/next_frame'}
execute if score @s aj.roll_straight_and_wing_back.frame matches 21.. run scoreboard players set @s aj.roll_straight_and_wing_back.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.roll_straight_and_wing_back.frame
execute at @s run function animated_java:terrible_sonic_bomber/animations/roll_straight_and_wing_back/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.roll_straight_and_wing_back.frame 1