# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tutankhamen/animations/beam_wait/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.beam_wait.frame 1