# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.twins_rubiel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'twins_rubiel', 'function_path': 'animated_java:twins_rubiel/animations/8_2_katana_throw/next_frame'}
execute if score @s aj.8_2_katana_throw.frame matches 25.. run scoreboard players set @s aj.8_2_katana_throw.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.8_2_katana_throw.frame
execute at @s run function animated_java:twins_rubiel/animations/8_2_katana_throw/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.8_2_katana_throw.frame 1