# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.frestchika.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'frestchika', 'function_path': 'animated_java:frestchika/variants/blue/apply'}
execute on passengers if entity @s[tag=aj.frestchika.bone.ahoge] run function animated_java:frestchika/variants/blue/zzz/0
execute on passengers if entity @s[tag=aj.frestchika.bone.side_tail_2] run function animated_java:frestchika/variants/blue/zzz/1
execute on passengers if entity @s[tag=aj.frestchika.bone.side_tail] run function animated_java:frestchika/variants/blue/zzz/2
execute on passengers if entity @s[tag=aj.frestchika.bone.backhair] run function animated_java:frestchika/variants/blue/zzz/3
execute on passengers if entity @s[tag=aj.frestchika.bone.head] run function animated_java:frestchika/variants/blue/zzz/4
execute on passengers if entity @s[tag=aj.frestchika.bone.right_1] run function animated_java:frestchika/variants/blue/zzz/5
execute on passengers if entity @s[tag=aj.frestchika.bone.right_2] run function animated_java:frestchika/variants/blue/zzz/6
execute on passengers if entity @s[tag=aj.frestchika.bone.right_3] run function animated_java:frestchika/variants/blue/zzz/7
execute on passengers if entity @s[tag=aj.frestchika.bone.right_wing] run function animated_java:frestchika/variants/blue/zzz/8
execute on passengers if entity @s[tag=aj.frestchika.bone.left_1] run function animated_java:frestchika/variants/blue/zzz/9
execute on passengers if entity @s[tag=aj.frestchika.bone.left_2] run function animated_java:frestchika/variants/blue/zzz/10
execute on passengers if entity @s[tag=aj.frestchika.bone.left_3] run function animated_java:frestchika/variants/blue/zzz/11
execute on passengers if entity @s[tag=aj.frestchika.bone.left_wing] run function animated_java:frestchika/variants/blue/zzz/12
execute on passengers if entity @s[tag=aj.frestchika.bone.body] run function animated_java:frestchika/variants/blue/zzz/13
execute on passengers if entity @s[tag=aj.frestchika.bone.right_hand] run function animated_java:frestchika/variants/blue/zzz/14
execute on passengers if entity @s[tag=aj.frestchika.bone.right_arm] run function animated_java:frestchika/variants/blue/zzz/15
execute on passengers if entity @s[tag=aj.frestchika.bone.left_hand] run function animated_java:frestchika/variants/blue/zzz/16
execute on passengers if entity @s[tag=aj.frestchika.bone.left_arm] run function animated_java:frestchika/variants/blue/zzz/17
execute on passengers if entity @s[tag=aj.frestchika.bone.right_foot] run function animated_java:frestchika/variants/blue/zzz/18
execute on passengers if entity @s[tag=aj.frestchika.bone.right_leg] run function animated_java:frestchika/variants/blue/zzz/19
execute on passengers if entity @s[tag=aj.frestchika.bone.left_foot] run function animated_java:frestchika/variants/blue/zzz/20
execute on passengers if entity @s[tag=aj.frestchika.bone.left_leg] run function animated_java:frestchika/variants/blue/zzz/21