# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.patriot_launcher.root] run return 0
execute on passengers if entity @s[tag=aj.patriot_launcher.data] unless data entity @s {data:{rigHash: '803247aaa339a67dc1e06ba2e615bc7cf6c0af6b9a96a15d53ab901c3b0e1b21'}} on vehicle run function animated_java:patriot_launcher/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1