# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tutankhamen.root] run return 0
execute on passengers if entity @s[tag=aj.tutankhamen.data] unless data entity @s {data:{rigHash: '986ad3229e13443581fef61f9f2fdd33691072a4302df43d9b68c175094ed379'}} on vehicle run function animated_java:tutankhamen/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1