# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.attack_magic_3_right_loop.frame matches 61.. run scoreboard players set @s aj.attack_magic_3_right_loop.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.attack_magic_3_right_loop.frame
execute at @s run function animated_java:illusion_of_loyalty/animations/attack_magic_3_right_loop/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.attack_magic_3_right_loop.frame 1