# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.blazing_inferno.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'blazing_inferno', 'function_path': 'animated_java:blazing_inferno/animations/pause_all'}
tag @s remove aj.blazing_inferno.animation.intro.playing
tag @s remove aj.blazing_inferno.animation.posing.playing
tag @s remove aj.blazing_inferno.animation.neutral_fighting.playing
tag @s remove aj.blazing_inferno.animation.death_loop.playing
tag @s remove aj.blazing_inferno.animation.attack_punch_1_right.playing
tag @s remove aj.blazing_inferno.animation.attack_punch_1_end.playing
tag @s remove aj.blazing_inferno.animation.attack_punch_1_left.playing
tag @s remove aj.blazing_inferno.animation.attack_shoot_1_right.playing
tag @s remove aj.blazing_inferno.animation.attack_shoot_1_left.playing
tag @s remove aj.blazing_inferno.animation.attack_shoot_2.playing
tag @s remove aj.blazing_inferno.animation.attack_fall.playing
tag @s remove aj.blazing_inferno.animation.attack_oraora_windup.playing
tag @s remove aj.blazing_inferno.animation.attack_oraora_loop.playing