# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.axia.root] run return 0
execute on passengers if entity @s[tag=aj.axia.data] unless data entity @s {data:{rigHash: '9f79df6395f54e68977d07f7d109c5b6f4778ffc1aa8ff977d97bfa78fba5836'}} on vehicle run function animated_java:axia/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1