# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.haruclaire_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'haruclaire_aj', 'function_path': 'animated_java:haruclaire_aj/animations/24_0_second_sword_line_first/next_frame'}
execute if score @s aj.24_0_second_sword_line_first.frame matches 191.. run scoreboard players set @s aj.24_0_second_sword_line_first.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.24_0_second_sword_line_first.frame
execute at @s run function animated_java:haruclaire_aj/animations/24_0_second_sword_line_first/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.24_0_second_sword_line_first.frame 1