# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.gargo_ex_machina.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gargo_ex_machina', 'function_path': 'animated_java:gargo_ex_machina/variants/blue/apply'}
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.eyes] run function animated_java:gargo_ex_machina/variants/blue/zzz/0
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.arm_right_3] run function animated_java:gargo_ex_machina/variants/blue/zzz/1
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.arm_right_2] run function animated_java:gargo_ex_machina/variants/blue/zzz/2
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.arm_right_1] run function animated_java:gargo_ex_machina/variants/blue/zzz/3
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.arm_right_0] run function animated_java:gargo_ex_machina/variants/blue/zzz/4
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.arm_left_3] run function animated_java:gargo_ex_machina/variants/blue/zzz/5
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.arm_left_2] run function animated_java:gargo_ex_machina/variants/blue/zzz/6
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.arm_left_1] run function animated_java:gargo_ex_machina/variants/blue/zzz/7
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.arm_left_0] run function animated_java:gargo_ex_machina/variants/blue/zzz/8
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.body_0] run function animated_java:gargo_ex_machina/variants/blue/zzz/9
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.body_1] run function animated_java:gargo_ex_machina/variants/blue/zzz/10
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.leg_right_2] run function animated_java:gargo_ex_machina/variants/blue/zzz/11
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.leg_right_1] run function animated_java:gargo_ex_machina/variants/blue/zzz/12
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.leg_right_0] run function animated_java:gargo_ex_machina/variants/blue/zzz/13
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.leg_left_2] run function animated_java:gargo_ex_machina/variants/blue/zzz/14
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.leg_left_1] run function animated_java:gargo_ex_machina/variants/blue/zzz/15
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.leg_left_0] run function animated_java:gargo_ex_machina/variants/blue/zzz/16
execute on passengers if entity @s[tag=aj.gargo_ex_machina.bone.body_2] run function animated_java:gargo_ex_machina/variants/blue/zzz/17