# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:frestchika/root/zzz/2 with entity @s data.locators.locator4
function animated_java:frestchika/root/zzz/4 with entity @s data.locators.locator5
function animated_java:frestchika/root/zzz/6 with entity @s data.locators.locator3
function animated_java:frestchika/root/zzz/8 with entity @s data.locators.locator2