# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.head] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_head
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.sword] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_sword
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.axe] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_axe
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.left_arm_2] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_left_arm_2
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.left_arm] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_left_arm
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.left_shoulder] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_left_shoulder
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.right_arm_2] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_right_arm_2
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.right_arm] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_right_arm
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.right_shoulder] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_right_shoulder
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.upper_body] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_upper_body
$execute on passengers if entity @s[tag=aj.grey_guardian.bone.body] run data modify entity @s {} merge from storage aj.grey_guardian:animations tacle_start.$(frame).bone_body