# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.behemoth_aj.root] run return 0
execute on passengers if entity @s[tag=aj.behemoth_aj.data] unless data entity @s {data:{rigHash: 'c90e1b77783e9954bea498abf28bd1aa93a50eba2e2075c3e1f680bd4f9996b2'}} on vehicle run function animated_java:behemoth_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1