# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.heiloang_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'heiloang_aj', 'function_path': 'animated_java:heiloang_aj/animations/6_1_sweep_breath_mirror/next_frame'}
execute if score @s aj.6_1_sweep_breath_mirror.frame matches 90.. run scoreboard players set @s aj.6_1_sweep_breath_mirror.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.6_1_sweep_breath_mirror.frame
execute at @s run function animated_java:heiloang_aj/animations/6_1_sweep_breath_mirror/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.6_1_sweep_breath_mirror.frame 1