# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.tutankhamen.locator', 'aj.tutankhamen.locator.weapon']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:tutankhamen/zzz/2
data modify entity @s data.locators.weapon.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.tutankhamen.locator', 'aj.tutankhamen.locator.body']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:tutankhamen/zzz/3
data modify entity @s data.locators.body.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.back_cape] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_back_cape set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.left_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.cape_left_back] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cape_left_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.cape_left_side] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cape_left_side set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.cape_right_back] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cape_right_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.cape_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_cape_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.weapon1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_weapon1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.right_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.body1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tutankhamen.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out