scoreboard objectives add aj.1_idle.frame dummy
scoreboard objectives add aj.pose.frame dummy
data remove storage aj.behemoth_aj:animations 1_idle
data remove storage aj.behemoth_aj:animations pose
# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.pose.frame dummy
scoreboard objectives add aj.1_idle.frame dummy