# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ic_capri_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ic_capri_aj', 'function_path': 'animated_java:ic_capri_aj/animations/2_attack/next_frame'}
execute if score @s aj.2_attack.frame matches 11.. run scoreboard players set @s aj.2_attack.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.2_attack.frame
execute at @s run function animated_java:ic_capri_aj/animations/2_attack/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.2_attack.frame 1