# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.illusion_of_loyalty.root] run return 0
execute on passengers if entity @s[tag=aj.illusion_of_loyalty.data] unless data entity @s {data:{rigHash: '7c150b9e8752483f5ae3cdf9d6c88bdb7ee90931d4e6dd11a82c735813f66aee'}} on vehicle run function animated_java:illusion_of_loyalty/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1