# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_radder1) { transformation: [-3f,0f,0f,-.09232f,0f,3f,0f,2.01868f,-0f,0f,-3f,-4.92357f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_body) { transformation: [-11.57963f,0f,0f,.00143f,0f,11.57963f,0f,-13.57142f,-0f,0f,-11.57963f,-.26742f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_aileron) { transformation: [-2.71892f,0f,1.26785f,-3.27024f,0f,3f,0f,.85671f,-1.26785f,0f,-2.71892f,-2.05404f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_hp1) { transformation: [-3f,0f,0f,-2.49982f,0f,3f,0f,.58483f,-0f,0f,-3f,-1.4879f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_hp2) { transformation: [-3f,0f,0f,-4.02921f,0f,3f,0f,.58483f,-0f,0f,-3f,-2.20107f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_wing) { transformation: [-3.11798f,0f,1.45394f,-.93607f,0f,3.44031f,0f,.77233f,-1.45394f,0f,-3.11798f,.48258f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_elevetor) { transformation: [-3f,0f,0f,.75143f,0f,3f,0f,.29421f,-0f,0f,-3f,-3.26742f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_elevetor) { transformation: [-3f,0f,0f,-.93607f,0f,3f,0f,.29421f,-0f,0f,-3f,-3.26742f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_aileron) { transformation: [-2.71892f,0f,-1.26785f,3.25553f,0f,3f,0f,.85671f,1.26785f,0f,-2.71892f,-2.13328f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_hp2) { transformation: [-3f,0f,0f,4.0145f,0f,3f,0f,.58483f,-0f,0f,-3f,-2.28031f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_hp1) { transformation: [-3f,0f,0f,2.48511f,0f,3f,0f,.58483f,-0f,0f,-3f,-1.56714f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_wing) { transformation: [-3.11798f,0f,-1.45394f,.75143f,0f,3.44031f,0f,.77233f,1.45394f,0f,-3.11798f,.48259f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }