# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tutankhamen.root] run return 0
execute on passengers if entity @s[tag=aj.tutankhamen.data] unless data entity @s {data:{rigHash: 'f21a90bcb891be39fcfb66a923c2f2ea41f1ab183dac5b6c7cb13e4bd22a623b'}} on vehicle run function animated_java:tutankhamen/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1