# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.convict.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'convict', 'function_path': 'animated_java:convict/animations/wait/next_frame'}
execute if score @s aj.wait.frame matches 52.. run scoreboard players set @s aj.wait.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.wait.frame
execute at @s run function animated_java:convict/animations/wait/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.wait.frame 1