# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.grey_guardian.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'grey_guardian', 'function_path': 'animated_java:grey_guardian/animations/attack5/stop'}
tag @s remove aj.grey_guardian.animation.attack5.playing
scoreboard players set @s aj.attack5.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:grey_guardian/animations/attack5/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only