# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.head3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_head3
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.arm_right_3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_arm_right_3
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.arm_right_2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_arm_right_2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.arm_left_3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_arm_left_3
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.arm_left_2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_arm_left_2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.body_3] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_body_3
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.leg_right2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_leg_right2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.leg_left2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_leg_left2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.tail2] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_tail2
$execute on passengers if entity @s[tag=aj.ic_tau_aj.bone.body_4] run data modify entity @s {} merge from storage aj.ic_tau_aj:animations 0_start.$(frame).bone_body_4