# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.24_0_second_sword_line_first.frame
function animated_java:haruclaire_aj/animations/24_0_second_sword_line_first/zzz/apply_frame with storage aj:temp
execute if score @s aj.24_0_second_sword_line_first.frame matches 190.. run return run function animated_java:haruclaire_aj/animations/24_0_second_sword_line_first/pause
scoreboard players add @s aj.24_0_second_sword_line_first.frame 1