# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.eclael.root] run return 0
execute on passengers if entity @s[tag=aj.eclael.data] unless data entity @s {data:{rigHash: 'fb392c2d7b4072ec7133dcfadbda66af748eb92f9e29aebb130605c8a8189238'}} on vehicle run function animated_java:eclael/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1