# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.heiloang_flare_aj.root] run return 0
execute on passengers if entity @s[tag=aj.heiloang_flare_aj.data] unless data entity @s {data:{rigHash: '575ef0701a8d596af3257c9c6a972a621a461f01b1ee990b4788a1e91db949db'}} on vehicle run function animated_java:heiloang_flare_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1