# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.heiloang_flare_aj.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:heiloang_flare_aj/as_root/pre_tick
execute if entity @s[tag=aj.heiloang_flare_aj.animation.spin.playing] run function animated_java:heiloang_flare_aj/animations/spin/zzz/on_tick
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:heiloang_flare_aj/as_root/post_tick