# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.wing_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.wing_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.wing_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.wing_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.staff] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_staff set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.arm_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.arm_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.arm_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.arm_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.himo_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_himo_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.himo_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_himo_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.himo_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_himo_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.himo_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_himo_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ponpon1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ponpon1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ponpon2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ponpon2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ponpon3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ponpon3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ponpon4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ponpon4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_edge_a1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_a1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_edge_a2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_a2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_edge_b1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_b1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_edge_b2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_b2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_edge_a3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_a3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_edge_a4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_a4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_edge_b3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_b3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_edge_b4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_b4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.ear_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.leg_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.leg_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.leg_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.leg_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.skirt_forward_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_forward_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.skirt_forward_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_forward_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.skirt_forward] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_forward set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.skirt_back_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_back_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.skirt_back_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_back_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.skirt_back] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.skirt_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.skirt_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.coat_downer] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coat_downer set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.body_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.book_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_book_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.book_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_book_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.book_loot_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_book_loot_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.book_left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_book_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.book_right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_book_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.book_loot_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_book_loot_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.ecual.node.air_staff_povit_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_air_staff_povit_1 set from storage aj:uuid main.out