# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.grey_guardian.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'grey_guardian', 'function_path': 'animated_java:grey_guardian/animations/pause_all'}
tag @s remove aj.grey_guardian.animation.wait.playing
tag @s remove aj.grey_guardian.animation.summon.playing
tag @s remove aj.grey_guardian.animation.move.playing
tag @s remove aj.grey_guardian.animation.backstep.playing
tag @s remove aj.grey_guardian.animation.attack1.playing
tag @s remove aj.grey_guardian.animation.attack2.playing
tag @s remove aj.grey_guardian.animation.attack3.playing
tag @s remove aj.grey_guardian.animation.attack4.playing
tag @s remove aj.grey_guardian.animation.attack5.playing
tag @s remove aj.grey_guardian.animation.tacle_start.playing
tag @s remove aj.grey_guardian.animation.tacle_start2.playing
tag @s remove aj.grey_guardian.animation.dead.playing