# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.frestchika.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'frestchika', 'function_path': 'animated_java:frestchika/animations/dash_left/stop'}
tag @s remove aj.frestchika.animation.dash_left.playing
scoreboard players set @s aj.dash_left.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:frestchika/animations/dash_left/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only