# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.node.head3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).3
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.node.arm_right3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).4
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.node.arm_left3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).5
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.node.body3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).2
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.node.tail_6] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).7
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.node.tail_5] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).6
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.node.root3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).1
$execute on passengers if entity @s[tag=aj.global.data] run data modify entity @s data.locators.pos merge from storage aj.ic_pisce_aj:animations pose.$(frame).l_8
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1