# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.sharkboss.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'sharkboss', 'function_path': 'animated_java:sharkboss/animations/watergun/play'}
tag @s add aj.sharkboss.animation.watergun.playing
scoreboard players set @s aj.watergun.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:sharkboss/animations/watergun/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only