# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.red_knight.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'red_knight', 'function_path': 'animated_java:red_knight/animations/neutral_air/apply_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.neutral_air.frame $(frame)
execute at @s run function animated_java:red_knight/animations/neutral_air/zzz/apply_frame with storage aj:temp