# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.terrible_sonic_bomber.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'terrible_sonic_bomber', 'function_path': 'animated_java:terrible_sonic_bomber/animations/wing_back/stop'}
tag @s remove aj.terrible_sonic_bomber.animation.wing_back.playing
scoreboard players set @s aj.wing_back.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:terrible_sonic_bomber/animations/wing_back/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only