# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.sheep_avenger.root] run return 0
execute on passengers if entity @s[tag=aj.sheep_avenger.data] unless data entity @s {data:{rigHash: '467ead40686a9b35b166a1206dd135542595c7891fbc84a44c0e7b55295ea104'}} on vehicle run function animated_java:sheep_avenger/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1