# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tiamat_aj.root] run return 0
execute on passengers if entity @s[tag=aj.tiamat_aj.data] unless data entity @s {data:{rigHash: '645268972b52e95698808c5fa4be208208dd932a3caa127e6197eba1607308a4'}} on vehicle run function animated_java:tiamat_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1