# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tiamat_aj.root] run return 0
execute on passengers if entity @s[tag=aj.tiamat_aj.data] unless data entity @s {data:{rigHash: 'f1c48b685678f59804c8a18aad8dbc002a49d0bd7aa68cd15ff0a1fd79a36ce5'}} on vehicle run function animated_java:tiamat_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1