# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.locator_nose.uuid
function animated_java:sharkboss/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator_body_0.uuid
function animated_java:sharkboss/zzz/execute with storage aj:temp