# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.gem_tnt_drone.node.head] run data modify entity @s {} merge from storage aj.gem_tnt_drone:animations attack_start.$(frame).3
$execute on passengers if entity @s[tag=aj.gem_tnt_drone.node.tail] run data modify entity @s {} merge from storage aj.gem_tnt_drone:animations attack_start.$(frame).4
$execute on passengers if entity @s[tag=aj.gem_tnt_drone.node.wing_right] run data modify entity @s {} merge from storage aj.gem_tnt_drone:animations attack_start.$(frame).5
$execute on passengers if entity @s[tag=aj.gem_tnt_drone.node.wing_left] run data modify entity @s {} merge from storage aj.gem_tnt_drone:animations attack_start.$(frame).6
$execute on passengers if entity @s[tag=aj.gem_tnt_drone.node.tnt] run data modify entity @s {} merge from storage aj.gem_tnt_drone:animations attack_start.$(frame).b_8
$execute on passengers if entity @s[tag=aj.gem_tnt_drone.node.body] run data modify entity @s {} merge from storage aj.gem_tnt_drone:animations attack_start.$(frame).2