# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.blazing_inferno.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'blazing_inferno', 'function_path': 'animated_java:blazing_inferno/animations/neutral_fighting/next_frame'}
execute if score @s aj.neutral_fighting.frame matches 21.. run scoreboard players set @s aj.neutral_fighting.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.neutral_fighting.frame
execute at @s run function animated_java:blazing_inferno/animations/neutral_fighting/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.neutral_fighting.frame 1