# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.twins_rubiel.root] run return 0
execute on passengers if entity @s[tag=aj.twins_rubiel.data] unless data entity @s {data:{rigHash: 'fc55b537a3ebf365696e821b123e9db61e7da83eed2653f0189e6b46f56b814a'}} on vehicle run function animated_java:twins_rubiel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1