# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.illusion_of_loyalty.root] run return 0
execute on passengers if entity @s[tag=aj.illusion_of_loyalty.data] unless data entity @s {data:{rigHash: '1b9d1f1815f718303442b84f6ada703cdf65dbfce2d3812cd3c71bef189585b3'}} on vehicle run function animated_java:illusion_of_loyalty/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1