# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.sharkboss.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'sharkboss', 'function_path': 'animated_java:sharkboss/animations/tornado/next_frame'}
execute if score @s aj.tornado.frame matches 115.. run scoreboard players set @s aj.tornado.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.tornado.frame
execute at @s run function animated_java:sharkboss/animations/tornado/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.tornado.frame 1