# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.frestchika.locator', 'aj.frestchika.locator.locator4']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:frestchika/zzz/2
data modify entity @s data.locators.locator4.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.frestchika.locator', 'aj.frestchika.locator.locator5']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:frestchika/zzz/3
data modify entity @s data.locators.locator5.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.frestchika.locator', 'aj.frestchika.locator.locator3']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:frestchika/zzz/4
data modify entity @s data.locators.locator3.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.frestchika.locator', 'aj.frestchika.locator.locator2']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:frestchika/zzz/5
data modify entity @s data.locators.locator2.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.ahoge] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ahoge set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.side_tail_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_side_tail_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.side_tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_side_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.backhair] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_backhair set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.right_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.right_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.left_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.left_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.right_item_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_right_item_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.right_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.left_item_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.item_display_left_item_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.left_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.frestchika.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out