# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:behemoth_aj/animations/3_1_casting/zzz/apply_frame {frame: 34}
scoreboard players add @s aj.3_1_casting.frame 1