# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.head3] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).4
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.arm_right_3] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).6
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.arm_right_2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).5
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.arm_left_3] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).8
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.arm_left_2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).7
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.body_3] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).3
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.leg_right2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).9
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.leg_left2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).a
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.tail2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).b
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.body_4] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).2
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1