# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ic_pisce_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ic_pisce_aj', 'function_path': 'animated_java:ic_pisce_aj/animations/pose/play'}
tag @s add aj.ic_pisce_aj.animation.pose.playing
scoreboard players set @s aj.pose.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:ic_pisce_aj/animations/pose/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only