# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lexiel.root] run return 0
execute on passengers if entity @s[tag=aj.lexiel.data] unless data entity @s {data:{rigHash: '48f1bb6a997865803b2edb04723465d868270f1d5e52035e7642398d94f10b27'}} on vehicle run function animated_java:lexiel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1