# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.illusion_of_loyalty.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'illusion_of_loyalty', 'function_path': 'animated_java:illusion_of_loyalty/animations/attack_magic_3_right/play'}
tag @s add aj.illusion_of_loyalty.animation.attack_magic_3_right.playing
scoreboard players set @s aj.attack_magic_3_right.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:illusion_of_loyalty/animations/attack_magic_3_right/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only