# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.gargo_ex_machina.locator', 'aj.gargo_ex_machina.locator.shadow']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:gargo_ex_machina/zzz/2
data modify entity @s data.locators.shadow.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.sword_back] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sword_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.eyes] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eyes set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.1_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_1_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.1_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_1_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.2_1_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_2_1_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.2_1_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_2_1_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.2_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_2_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.2_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_2_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.3_1_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_3_1_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.3_1_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_3_1_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.3_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_3_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.3_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_3_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.4_1_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_4_1_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.4_1_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_4_1_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.4_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_4_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.4_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_4_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.5_1_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_5_1_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.5_1_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_5_1_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.5_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_5_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.5_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_5_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.6_1_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_6_1_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.6_1_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_6_1_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.6_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_6_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.6_2_r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_6_2_r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.6_2_l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_6_2_l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.6_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_6_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.7_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_7_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.8_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_8_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.9l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_9l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.9r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_9r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.10r_1_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_10r_1_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.10r_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_10r_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.10r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_10r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.10l_1_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_10l_1_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.10l_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_10l_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.10l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_10l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.11r] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_11r set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.11l] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_11l set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.sword] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sword set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.arm_right_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.arm_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.arm_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.arm_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.arm_left_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.arm_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.arm_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.arm_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.body_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.leg_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.leg_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.leg_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.leg_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.leg_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.leg_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.body_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gargo_ex_machina.node.sign_head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sign_head set from storage aj:uuid main.out