# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.shadow.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp