# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s shadow_radius set value 5f
data modify entity @s shadow_strength set value 1f
data modify entity @s view_range set value 16f
tag @s add CO.Shadow