# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_2.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_3.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_1.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_0.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.muzzle.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_right_0.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_right_1.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_right_2.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_left_3.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_left_4.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.hitbox_left_5.uuid
function animated_java:gargo_ex_machina/zzz/execute with storage aj:temp