# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.grey_guardian.root] run return 0
execute on passengers if entity @s[tag=aj.grey_guardian.data] unless data entity @s {data:{rigHash: 'bc88d0ad4db784bd53299f21cfd1dc361111e7180e3b38751e20c29efd83dc8d'}} on vehicle run function animated_java:grey_guardian/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1