# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.louvert.locator', 'aj.louvert.locator.locator']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:louvert/zzz/2
data modify entity @s data.locators.locator.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.louvert.locator', 'aj.louvert.locator.locator2']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:louvert/zzz/3
data modify entity @s data.locators.locator2.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.coat_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coat_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.coat_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coat_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.coat_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coat_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.right_leg_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.right_leg_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.left_leg_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.left_leg_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.sword_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sword_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.right_arm_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.right_arm_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.sword_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sword_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.left_arm_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.left_arm_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.wing_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.wing_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.louvert.bone.body_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_0 set from storage aj:uuid main.out