# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.twins_sapphiel.root] run return 0
execute on passengers if entity @s[tag=aj.twins_sapphiel.data] unless data entity @s {data:{rigHash: '4750b88d84ab42af2752b06e99c573a1eb60b44c10349fc7565ba7931064e87d'}} on vehicle run function animated_java:twins_sapphiel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1