# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.twins_rubiel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'twins_rubiel', 'function_path': 'animated_java:twins_rubiel/animations/6_3_katana_sheathe_counter/play'}
tag @s add aj.twins_rubiel.animation.6_3_katana_sheathe_counter.playing
scoreboard players set @s aj.6_3_katana_sheathe_counter.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:twins_rubiel/animations/6_3_katana_sheathe_counter/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only