# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:sharkboss/animations/move_loop/zzz/apply_frame {frame: 16}
scoreboard players add @s aj.move_loop.frame 1