# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.hat] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.haruclaire_rod] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_haruclaire_rod set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.haruclaire_korigori] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_haruclaire_korigori set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.haruclaire_sword] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_haruclaire_sword set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.arm_belt_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_belt_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.arm_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.arm_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.arm_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.hat_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hat_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.arm_belt_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_belt_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.arm_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.arm_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.arm_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.wing_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.wing_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.body_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.leg_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.leg_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.leg_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.leg_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.belt_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_belt_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.belt_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_belt_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.belt_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_belt_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.belt_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_belt_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.parker_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_parker_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.haruclaire_rod_air] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_haruclaire_rod_air set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.hato_head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hato_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.hato_tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hato_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.hato_wing_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hato_wing_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.hato_wing_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hato_wing_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.haruclaire_aj.bone.hato_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hato_body set from storage aj:uuid main.out