# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tiamat_aj/animations/1_idle/zzz/apply_frame {frame: 45}
scoreboard players add @s aj.1_idle.frame 1