# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.lexiel.root] run return 0
execute on passengers if entity @s[tag=aj.lexiel.data] unless data entity @s {data:{rigHash: '63058fd774bc70458760c23fc92154220f35c280f0f1751eb6369dfb17f0ccc3'}} on vehicle run function animated_java:lexiel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1