# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.bone.head3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).bone_head3
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.bone.arm_right3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).bone_arm_right3
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.bone.arm_left3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).bone_arm_left3
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.bone.body3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).bone_body3
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.bone.tail_6] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).bone_tail_6
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.bone.tail_5] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).bone_tail_5
$execute on passengers run data modify entity @s[tag=aj.ic_pisce_aj.bone.root3] {} merge from storage aj.ic_pisce_aj:animations pose.$(frame).bone_root3
$execute on passengers if entity @s[tag=aj.data] run data modify entity @s data.locators.pos merge from storage aj.ic_pisce_aj:animations pose.$(frame).locator_pos
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1