# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blazing_inferno.root] run return 0
execute on passengers if entity @s[tag=aj.blazing_inferno.data] unless data entity @s {data:{rigHash: '752e66ca6c2efb7790fd6479261203a63df92bdc4ec5f2a9123105595bff993b'}} on vehicle run function animated_java:blazing_inferno/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1