# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.eclael.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'eclael', 'function_path': 'animated_java:eclael/animations/19_2_latter_attack_iai_2/play'}
tag @s add aj.eclael.animation.19_2_latter_attack_iai_2.playing
scoreboard players set @s aj.19_2_latter_attack_iai_2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:eclael/animations/19_2_latter_attack_iai_2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only