# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.head] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).2
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.body] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).3
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.left_hand] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).5
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.left_arm] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).4
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.weapon] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).8
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.right_hand] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).7
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.right_arm] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).6
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.waist] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).a
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.left_foot] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).c
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.left_leg] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).b
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.right_foot] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).e
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.right_leg] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).d
$execute on passengers run data modify entity @s[tag=aj.red_knight.node.weapon_ground] {} merge from storage aj.red_knight:animations attack_melee_1.$(frame).f
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1