# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tiamat_aj.root] run return 0
execute on passengers if entity @s[tag=aj.tiamat_aj.data] unless data entity @s {data:{rigHash: '519f5a18b808b2db214b8698a5482e20944a97da3a3558df4865681b2b60a897'}} on vehicle run function animated_java:tiamat_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1