# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tiamat_aj.root] run return 0
execute on passengers if entity @s[tag=aj.tiamat_aj.data] unless data entity @s {data:{rigHash: 'd19151e10e3ac3e714445d1400262bb25501cc53ef9b0d8af2b3a18a081acfac'}} on vehicle run function animated_java:tiamat_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1