# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.red_knight.root] run return 0
execute on passengers if entity @s[tag=aj.red_knight.data] unless data entity @s {data:{rigHash: '91a35745280908d538613dd804136749594d2c65fb8bd22e34450d5eace626d6'}} on vehicle run function animated_java:red_knight/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1