# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.red_knight.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:red_knight/as_root/pre_tick
execute if entity @s[tag=aj.red_knight.animation.neutral_ground.playing] run function animated_java:red_knight/animations/neutral_ground/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.neutral_air.playing] run function animated_java:red_knight/animations/neutral_air/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.attack_melee_1.playing] run function animated_java:red_knight/animations/attack_melee_1/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.attack_melee_2.playing] run function animated_java:red_knight/animations/attack_melee_2/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.attack_melee_3.playing] run function animated_java:red_knight/animations/attack_melee_3/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.attack_melee_3_immediate.playing] run function animated_java:red_knight/animations/attack_melee_3_immediate/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.attack_rising_slash.playing] run function animated_java:red_knight/animations/attack_rising_slash/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.attack_projectile_1.playing] run function animated_java:red_knight/animations/attack_projectile_1/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.attack_fallstab_windup.playing] run function animated_java:red_knight/animations/attack_fallstab_windup/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.attack_fallstab_landing.playing] run function animated_java:red_knight/animations/attack_fallstab_landing/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.summon_1.playing] run function animated_java:red_knight/animations/summon_1/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.summon_2.playing] run function animated_java:red_knight/animations/summon_2/zzz/on_tick
execute if entity @s[tag=aj.red_knight.animation.death2.playing] run function animated_java:red_knight/animations/death2/zzz/on_tick
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:red_knight/as_root/post_tick