# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.patriot_launcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'patriot_launcher', 'function_path': 'animated_java:patriot_launcher/animations/pause_all'}
tag @s remove aj.patriot_launcher.animation.default.playing
tag @s remove aj.patriot_launcher.animation.launch.playing
tag @s remove aj.patriot_launcher.animation.reload.playing
tag @s remove aj.patriot_launcher.animation.destroy.playing
tag @s remove aj.patriot_launcher.animation.rotation.playing
tag @s remove aj.patriot_launcher.animation.rotation_no_missile.playing