# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.head] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_head
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.body] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_body
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.left_hand] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_left_hand
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.left_arm] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_left_arm
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.weapon] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_weapon
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.right_hand] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_right_hand
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.right_arm] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_right_arm
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.waist] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_waist
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.left_foot] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_left_foot
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.left_leg] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_left_leg
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.right_foot] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_right_foot
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.right_leg] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_right_leg
$execute on passengers run data modify entity @s[tag=aj.red_knight.bone.weapon_ground] {} merge from storage aj.red_knight:animations neutral_air.$(frame).bone_weapon_ground
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1