# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.halo] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_halo set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.ruby_katana] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ruby_katana set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.root_taiken] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_root_taiken set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.root_scythe] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_root_scythe set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.arm_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.arm_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.sapphie_katana] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sapphie_katana set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.ruby_saya] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ruby_saya set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.ruby_sheathe] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ruby_sheathe set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.arm_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.arm_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.wing_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.wing_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.wing_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.wing_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.tail_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.tail_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.tail_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.uwagi_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_uwagi_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.uwagi_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_uwagi_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.uwagi] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_uwagi set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.body_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.leg_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.leg_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.leg_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.leg_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.saya_belt] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_saya_belt set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.saya] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_saya set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.twins_rubiel.node.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out