# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.illusion_of_loyalty.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'illusion_of_loyalty', 'function_path': 'animated_java:illusion_of_loyalty/animations/pause_all'}
tag @s remove aj.illusion_of_loyalty.animation.neutral_air.playing
tag @s remove aj.illusion_of_loyalty.animation.attack_magic_1_right.playing
tag @s remove aj.illusion_of_loyalty.animation.attack_magic_1_left.playing
tag @s remove aj.illusion_of_loyalty.animation.attack_magic_2_left.playing
tag @s remove aj.illusion_of_loyalty.animation.attack_magic_2_right.playing
tag @s remove aj.illusion_of_loyalty.animation.attack_magic_3_right.playing
tag @s remove aj.illusion_of_loyalty.animation.attack_magic_3_right_loop.playing
tag @s remove aj.illusion_of_loyalty.animation.dodge_back.playing