# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.karmic.node.head] {} merge from storage aj.karmic:animations spin.$(frame).2
$execute on passengers run data modify entity @s[tag=aj.karmic.node.rightscythe_handle] {} merge from storage aj.karmic:animations spin.$(frame).6
$execute on passengers run data modify entity @s[tag=aj.karmic.node.sword] {} merge from storage aj.karmic:animations spin.$(frame).7
$execute on passengers run data modify entity @s[tag=aj.karmic.node.righthand] {} merge from storage aj.karmic:animations spin.$(frame).4
$execute on passengers run data modify entity @s[tag=aj.karmic.node.rightarm] {} merge from storage aj.karmic:animations spin.$(frame).3
$execute on passengers run data modify entity @s[tag=aj.karmic.node.gun] {} merge from storage aj.karmic:animations spin.$(frame).a
$execute on passengers run data modify entity @s[tag=aj.karmic.node.leftscythe_handle] {} merge from storage aj.karmic:animations spin.$(frame).c
$execute on passengers run data modify entity @s[tag=aj.karmic.node.lefthand] {} merge from storage aj.karmic:animations spin.$(frame).9
$execute on passengers run data modify entity @s[tag=aj.karmic.node.leftarm] {} merge from storage aj.karmic:animations spin.$(frame).8
$execute on passengers run data modify entity @s[tag=aj.karmic.node.body] {} merge from storage aj.karmic:animations spin.$(frame).1
$execute on passengers run data modify entity @s[tag=aj.karmic.node.leftfeet] {} merge from storage aj.karmic:animations spin.$(frame).f
$execute on passengers run data modify entity @s[tag=aj.karmic.node.leftleg] {} merge from storage aj.karmic:animations spin.$(frame).e
$execute on passengers run data modify entity @s[tag=aj.karmic.node.rightfeet] {} merge from storage aj.karmic:animations spin.$(frame).h
$execute on passengers run data modify entity @s[tag=aj.karmic.node.rightleg] {} merge from storage aj.karmic:animations spin.$(frame).g
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1