# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.patriot_launcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'patriot_launcher', 'function_path': 'animated_java:patriot_launcher/animations/rotation_no_missile/next_frame'}
execute if score @s aj.rotation_no_missile.frame matches 361.. run scoreboard players set @s aj.rotation_no_missile.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.rotation_no_missile.frame
execute at @s run function animated_java:patriot_launcher/animations/rotation_no_missile/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.rotation_no_missile.frame 1