# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.patriot_launcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'patriot_launcher', 'function_path': 'animated_java:patriot_launcher/animations/rotation_no_missile/stop'}
tag @s remove aj.patriot_launcher.animation.rotation_no_missile.playing
scoreboard players set @s aj.rotation_no_missile.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:patriot_launcher/animations/rotation_no_missile/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only