# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.gargo_ex_machina.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gargo_ex_machina', 'function_path': 'animated_java:gargo_ex_machina/animations/call_drone_first/next_frame'}
execute if score @s aj.call_drone_first.frame matches 111.. run scoreboard players set @s aj.call_drone_first.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.call_drone_first.frame
execute at @s run function animated_java:gargo_ex_machina/animations/call_drone_first/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.call_drone_first.frame 1