# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.gem_tnt_drone.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gem_tnt_drone', 'function_path': 'animated_java:gem_tnt_drone/animations/remove/next_frame'}
execute if score @s aj.remove.frame matches 21.. run scoreboard players set @s aj.remove.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.remove.frame
execute at @s run function animated_java:gem_tnt_drone/animations/remove/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.remove.frame 1