# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.heiloang_aj.root] run return 0
execute on passengers if entity @s[tag=aj.heiloang_aj.data] unless data entity @s {data:{rigHash: '6f795ee0f1f0b71e8d0fc1f7feb727679b8ac6bac14bae1ab2829b47835c23b0'}} on vehicle run function animated_java:heiloang_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1