# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.heiloang_aj.root] run return 0
execute on passengers if entity @s[tag=aj.heiloang_aj.data] unless data entity @s {data:{rigHash: '27c0e2f2709f385c3fe85d811760eba0c3c75138cd434bd8beeebed62613e3a8'}} on vehicle run function animated_java:heiloang_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1