# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.heiloang_aj.root] run return 0
execute on passengers if entity @s[tag=aj.heiloang_aj.data] unless data entity @s {data:{rigHash: '3d04f81ce196ae70ede5758e6b4b2504932d6197d0f0e85cef12e7e8a324d615'}} on vehicle run function animated_java:heiloang_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1