# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.red_knight.node.head] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).2
$execute on passengers if entity @s[tag=aj.red_knight.node.body] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).3
$execute on passengers if entity @s[tag=aj.red_knight.node.left_hand] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).5
$execute on passengers if entity @s[tag=aj.red_knight.node.left_arm] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).4
$execute on passengers if entity @s[tag=aj.red_knight.node.weapon] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).8
$execute on passengers if entity @s[tag=aj.red_knight.node.right_hand] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).7
$execute on passengers if entity @s[tag=aj.red_knight.node.right_arm] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).6
$execute on passengers if entity @s[tag=aj.red_knight.node.waist] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).a
$execute on passengers if entity @s[tag=aj.red_knight.node.left_foot] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).c
$execute on passengers if entity @s[tag=aj.red_knight.node.left_leg] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).b
$execute on passengers if entity @s[tag=aj.red_knight.node.right_foot] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).e
$execute on passengers if entity @s[tag=aj.red_knight.node.right_leg] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).d
$execute on passengers if entity @s[tag=aj.red_knight.node.weapon_ground] run data modify entity @s {} merge from storage aj.red_knight:animations attack_fallstab_windup.$(frame).f