# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.convict.root] run return 0
execute on passengers if entity @s[tag=aj.convict.data] unless data entity @s {data:{rigHash: 'eb2fc566373dcb19798b36e99001fcb7b507150ac6521d866a7508ec96cf8e9e'}} on vehicle run function animated_java:convict/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1