# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.grey_guardian.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:grey_guardian/as_root/pre_tick
execute if entity @s[tag=aj.grey_guardian.animation.wait.playing] run function animated_java:grey_guardian/animations/wait/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.summon.playing] run function animated_java:grey_guardian/animations/summon/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.move.playing] run function animated_java:grey_guardian/animations/move/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.backstep.playing] run function animated_java:grey_guardian/animations/backstep/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.attack1.playing] run function animated_java:grey_guardian/animations/attack1/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.attack2.playing] run function animated_java:grey_guardian/animations/attack2/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.attack3.playing] run function animated_java:grey_guardian/animations/attack3/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.attack4.playing] run function animated_java:grey_guardian/animations/attack4/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.attack5.playing] run function animated_java:grey_guardian/animations/attack5/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.tacle_start.playing] run function animated_java:grey_guardian/animations/tacle_start/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.tacle_start2.playing] run function animated_java:grey_guardian/animations/tacle_start2/zzz/on_tick
execute if entity @s[tag=aj.grey_guardian.animation.dead.playing] run function animated_java:grey_guardian/animations/dead/zzz/on_tick
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:grey_guardian/as_root/post_tick