# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.convict.node.left_leg_2] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).2
$execute on passengers if entity @s[tag=aj.convict.node.left_leg] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).1
$execute on passengers if entity @s[tag=aj.convict.node.right_leg_2] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).4
$execute on passengers if entity @s[tag=aj.convict.node.right_leg] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).3
$execute on passengers if entity @s[tag=aj.convict.node.head] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).6
$execute on passengers if entity @s[tag=aj.convict.node.left_axe] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).9
$execute on passengers if entity @s[tag=aj.convict.node.left_arm_2] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).8
$execute on passengers if entity @s[tag=aj.convict.node.left_arm] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).7
$execute on passengers if entity @s[tag=aj.convict.node.right_axe] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).c
$execute on passengers if entity @s[tag=aj.convict.node.right_arm_2] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).b
$execute on passengers if entity @s[tag=aj.convict.node.right_arm] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).a
$execute on passengers if entity @s[tag=aj.convict.node.body] run data modify entity @s {} merge from storage aj.convict:animations attack6_1.$(frame).5