# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.louvert.root] run return 0
execute on passengers if entity @s[tag=aj.louvert.data] unless data entity @s {data:{rigHash: 'ef989956759a94e4b678dcf5c029635b11894e8213c992c08d8ad96afdf0d0e0'}} on vehicle run function animated_java:louvert/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1