# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.haruclaire_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'haruclaire_aj', 'function_path': 'animated_java:haruclaire_aj/animations/29_0_second_move_forward/next_frame'}
execute if score @s aj.29_0_second_move_forward.frame matches 2.. run scoreboard players set @s aj.29_0_second_move_forward.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.29_0_second_move_forward.frame
execute at @s run function animated_java:haruclaire_aj/animations/29_0_second_move_forward/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.29_0_second_move_forward.frame 1