# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.heiloang_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'heiloang_aj', 'function_path': 'animated_java:heiloang_aj/animations/pause_all'}
tag @s remove aj.heiloang_aj.animation.000_pose.playing
tag @s remove aj.heiloang_aj.animation.1_idle.playing
tag @s remove aj.heiloang_aj.animation.2_0_common_cast_start.playing
tag @s remove aj.heiloang_aj.animation.2_1_common_casting.playing
tag @s remove aj.heiloang_aj.animation.2_2_common_invoke.playing
tag @s remove aj.heiloang_aj.animation.2_2_common_invoke2.playing
tag @s remove aj.heiloang_aj.animation.2_3_common_order.playing
tag @s remove aj.heiloang_aj.animation.2_4_common_disaster.playing
tag @s remove aj.heiloang_aj.animation.3_0_hellfire_start.playing
tag @s remove aj.heiloang_aj.animation.3_1_hellfire_shoot.playing
tag @s remove aj.heiloang_aj.animation.3_2_hellfire_shoot_end.playing
tag @s remove aj.heiloang_aj.animation.4_blizzard.playing
tag @s remove aj.heiloang_aj.animation.5_1_move_start.playing
tag @s remove aj.heiloang_aj.animation.5_2_move.playing
tag @s remove aj.heiloang_aj.animation.5_2_move2.playing
tag @s remove aj.heiloang_aj.animation.6_sweep_breath.playing
tag @s remove aj.heiloang_aj.animation.6_sweep_breath2.playing
tag @s remove aj.heiloang_aj.animation.7_1_dive_start.playing
tag @s remove aj.heiloang_aj.animation.7_2_dive.playing
tag @s remove aj.heiloang_aj.animation.7_3_dive_end.playing
tag @s remove aj.heiloang_aj.animation.7_z_dive_test.playing
tag @s remove aj.heiloang_aj.animation.8_1_move_flare.playing
tag @s remove aj.heiloang_aj.animation.2_0_common_cast_bak.playing
tag @s remove aj.heiloang_aj.animation.99_disaster_cast.playing
tag @s remove aj.heiloang_aj.animation.99_disaster.playing
tag @s remove aj.heiloang_aj.animation.99_disaster2.playing