# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_radder1) { transformation: [-3f,0f,0f,-.09232f,0f,3f,0f,2.01868f,-0f,0f,-3f,-4.92357f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_body) { transformation: [-11.57963f,0f,0f,.00143f,0f,11.57963f,0f,-13.57142f,-0f,0f,-11.57963f,-.26742f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_aileron) { transformation: [-2.89778f,0f,.77646f,-3.67526f,0f,3f,0f,.85671f,-.77646f,0f,-2.89778f,-1.61018f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_hp1) { transformation: [-3f,0f,0f,-2.81823f,0f,3f,0f,.58483f,-0f,0f,-3f,-1.18642f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_hp2) { transformation: [-3f,0f,0f,-4.44823f,0f,3f,0f,.58483f,-0f,0f,-3f,-1.62318f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_wing) { transformation: [-3.32308f,0f,.89042f,-.93607f,0f,3.44031f,0f,.77233f,-.89042f,0f,-3.32308f,.48258f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_elevetor) { transformation: [-3f,0f,0f,.75143f,0f,3f,0f,.29421f,-0f,0f,-3f,-3.26742f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_elevetor) { transformation: [-3f,0f,0f,-.93607f,0f,3f,0f,.29421f,-0f,0f,-3f,-3.26742f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_aileron) { transformation: [-2.89778f,0f,-.77646f,3.67173f,0f,3f,0f,.85671f,.77646f,0f,-2.89778f,-1.65871f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_hp2) { transformation: [-3f,0f,0f,4.4447f,0f,3f,0f,.58483f,-0f,0f,-3f,-1.67171f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_hp1) { transformation: [-3f,0f,0f,2.8147f,0f,3f,0f,.58483f,-0f,0f,-3f,-1.23495f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_wing) { transformation: [-3.32308f,0f,-.89042f,.75143f,0f,3.44031f,0f,.77233f,.89042f,0f,-3.32308f,.48259f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }