# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.twins_sapphiel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'twins_sapphiel', 'function_path': 'animated_java:twins_sapphiel/animations/31_1_sync_crossfire_1/play'}
tag @s add aj.twins_sapphiel.animation.31_1_sync_crossfire_1.playing
scoreboard players set @s aj.31_1_sync_crossfire_1.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:twins_sapphiel/animations/31_1_sync_crossfire_1/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only