# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.head3] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_head3
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.arm_right_3] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_arm_right_3
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.arm_right_2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_arm_right_2
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.arm_left_3] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_arm_left_3
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.arm_left_2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_arm_left_2
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.body_3] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_body_3
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.leg_right2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_leg_right2
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.leg_left2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_leg_left2
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.tail2] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_tail2
$execute on passengers run data modify entity @s[tag=aj.ic_tau_aj.node.body_4] {} merge from storage aj.ic_tau_aj:animations 1_idle.$(frame).bone_body_4
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1