# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.radder1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_radder1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.right_aileron] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_aileron set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.right_hp1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hp1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.right_hp2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hp2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.right_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.left_elevetor] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_elevetor set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.right_elevetor] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_elevetor set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.left_aileron] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_aileron set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.left_hp2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hp2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.left_hp1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hp1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.terrible_sonic_bomber.node.left_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_wing set from storage aj:uuid main.out