# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.3_2_katana_spear_damage.frame
function animated_java:twins_rubiel/animations/3_2_katana_spear_damage/zzz/apply_frame with storage aj:temp
execute if score @s aj.3_2_katana_spear_damage.frame matches 45.. run return run function animated_java:twins_rubiel/animations/3_2_katana_spear_damage/pause
scoreboard players add @s aj.3_2_katana_spear_damage.frame 1