# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ic_pisce_aj.root] run return 0
execute on passengers if entity @s[tag=aj.ic_pisce_aj.data] unless data entity @s {data:{rigHash: '31efbdde7d8ca8474c31b3b32ecd5a2a00c66f30ad209fc1c29fb52db1a65c35'}} on vehicle run function animated_java:ic_pisce_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1