# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ic_pisce_aj.root] run return 0
execute on passengers if entity @s[tag=aj.ic_pisce_aj.data] unless data entity @s {data:{rigHash: 'd074200f4de01162c9cde80d91f6e2d04e3d43f96a024d3e0af408b5c1fa1d71'}} on vehicle run function animated_java:ic_pisce_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1