# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.louvert.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'louvert', 'function_path': 'animated_java:louvert/animations/06_4_move_attack/play'}
tag @s add aj.louvert.animation.06_4_move_attack.playing
scoreboard players set @s aj.06_4_move_attack.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:louvert/animations/06_4_move_attack/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only