# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tutankhamen/animations/beam_long_charge/zzz/apply_frame {frame: 17}
scoreboard players add @s aj.beam_long_charge.frame 1