# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:blazing_inferno/animations/attack_oraora_loop/zzz/apply_frame {frame: 4}
scoreboard players add @s aj.attack_oraora_loop.frame 1