# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.twins_rubiel.root] run return 0
execute on passengers if entity @s[tag=aj.twins_rubiel.data] unless data entity @s {data:{rigHash: 'c666f69740eee73df48e88313307a4d5db518335152b2e7ead15ba92f92aada9'}} on vehicle run function animated_java:twins_rubiel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1