# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.twins_rubiel.root] run return 0
execute on passengers if entity @s[tag=aj.twins_rubiel.data] unless data entity @s {data:{rigHash: '9cca6dce2bc3d673eb31b09f6e7e4b05388770f045a1032404d655c41118919d'}} on vehicle run function animated_java:twins_rubiel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1