# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.twins_rubiel.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:twins_rubiel/as_root/pre_tick
execute if entity @s[tag=aj.twins_rubiel.animation.0_0_start.playing] run function animated_java:twins_rubiel/animations/0_0_start/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.1_0_katana_start.playing] run function animated_java:twins_rubiel/animations/1_0_katana_start/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.2_0_0_idle_katana_normal.playing] run function animated_java:twins_rubiel/animations/2_0_0_idle_katana_normal/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.2_0_1_idle_katana_fun.playing] run function animated_java:twins_rubiel/animations/2_0_1_idle_katana_fun/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.2_0_2_idle_katana_angry.playing] run function animated_java:twins_rubiel/animations/2_0_2_idle_katana_angry/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.2_1_katana_guard.playing] run function animated_java:twins_rubiel/animations/2_1_katana_guard/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.3_0_katana_moveslash.playing] run function animated_java:twins_rubiel/animations/3_0_katana_moveslash/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.3_1_katana_move_to_spear.playing] run function animated_java:twins_rubiel/animations/3_1_katana_move_to_spear/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.3_2_katana_spear_damage.playing] run function animated_java:twins_rubiel/animations/3_2_katana_spear_damage/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.3_3_katana_vacu_slash.playing] run function animated_java:twins_rubiel/animations/3_3_katana_vacu_slash/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.4_0_katana_slash_double.playing] run function animated_java:twins_rubiel/animations/4_0_katana_slash_double/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.5_0_katana_warp_0.playing] run function animated_java:twins_rubiel/animations/5_0_katana_warp_0/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.5_0_katana_warp_1.playing] run function animated_java:twins_rubiel/animations/5_0_katana_warp_1/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.5_0_katana_warp_2.playing] run function animated_java:twins_rubiel/animations/5_0_katana_warp_2/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.5_0_katana_warp_3.playing] run function animated_java:twins_rubiel/animations/5_0_katana_warp_3/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.6_0_katana_sheathe.playing] run function animated_java:twins_rubiel/animations/6_0_katana_sheathe/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.6_1_katana_sheathe_wait_cross.playing] run function animated_java:twins_rubiel/animations/6_1_katana_sheathe_wait_cross/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.6_2_katana_sheathe_cross.playing] run function animated_java:twins_rubiel/animations/6_2_katana_sheathe_cross/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.6_3_katana_sheathe_counter.playing] run function animated_java:twins_rubiel/animations/6_3_katana_sheathe_counter/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.6_4_katana_sheathe_damage.playing] run function animated_java:twins_rubiel/animations/6_4_katana_sheathe_damage/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.7_0_katana_jumpslash.playing] run function animated_java:twins_rubiel/animations/7_0_katana_jumpslash/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.7_1_katana_horizon.playing] run function animated_java:twins_rubiel/animations/7_1_katana_horizon/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.7_2_katana_horizon_w.playing] run function animated_java:twins_rubiel/animations/7_2_katana_horizon_w/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.7_3_katana_dashattack_to_cross.playing] run function animated_java:twins_rubiel/animations/7_3_katana_dashattack_to_cross/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.7_4_katana_backjump.playing] run function animated_java:twins_rubiel/animations/7_4_katana_backjump/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.8_0_katana_throw_start_normal.playing] run function animated_java:twins_rubiel/animations/8_0_katana_throw_start_normal/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.8_1_katana_throw_failed.playing] run function animated_java:twins_rubiel/animations/8_1_katana_throw_failed/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.8_2_katana_throw.playing] run function animated_java:twins_rubiel/animations/8_2_katana_throw/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.8_3_katana_throw_pursuit.playing] run function animated_java:twins_rubiel/animations/8_3_katana_throw_pursuit/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.11_0_scythe_start.playing] run function animated_java:twins_rubiel/animations/11_0_scythe_start/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.12_0_0_idle_scythe_normal.playing] run function animated_java:twins_rubiel/animations/12_0_0_idle_scythe_normal/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.12_0_1_idle_scythe_fun.playing] run function animated_java:twins_rubiel/animations/12_0_1_idle_scythe_fun/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.12_0_0_idle_scythe_angry.playing] run function animated_java:twins_rubiel/animations/12_0_0_idle_scythe_angry/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.13_0_scythe_warp_0.playing] run function animated_java:twins_rubiel/animations/13_0_scythe_warp_0/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.13_1_scythe_warp_1_slash.playing] run function animated_java:twins_rubiel/animations/13_1_scythe_warp_1_slash/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.13_2_scythe_warp_2_upper.playing] run function animated_java:twins_rubiel/animations/13_2_scythe_warp_2_upper/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.13_3_scythe_warp_3_throw.playing] run function animated_java:twins_rubiel/animations/13_3_scythe_warp_3_throw/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.13_4_scythe_warp_4_end.playing] run function animated_java:twins_rubiel/animations/13_4_scythe_warp_4_end/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.30_0_sync_goalong.playing] run function animated_java:twins_rubiel/animations/30_0_sync_goalong/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.31_0_sync_crossfire_0.playing] run function animated_java:twins_rubiel/animations/31_0_sync_crossfire_0/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.31_1_sync_crossfire_1.playing] run function animated_java:twins_rubiel/animations/31_1_sync_crossfire_1/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.32_0_sync_throwattack_0.playing] run function animated_java:twins_rubiel/animations/32_0_sync_throwattack_0/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.32_0_sync_throwattack_1.playing] run function animated_java:twins_rubiel/animations/32_0_sync_throwattack_1/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.40_0_damage.playing] run function animated_java:twins_rubiel/animations/40_0_damage/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.40_1_damage_down.playing] run function animated_java:twins_rubiel/animations/40_1_damage_down/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.40_2_damage_end.playing] run function animated_java:twins_rubiel/animations/40_2_damage_end/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.40_3_damage_stun_start.playing] run function animated_java:twins_rubiel/animations/40_3_damage_stun_start/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.40_4_damage_stun.playing] run function animated_java:twins_rubiel/animations/40_4_damage_stun/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.41_0_cover.playing] run function animated_java:twins_rubiel/animations/41_0_cover/zzz/on_tick
execute if entity @s[tag=aj.twins_rubiel.animation.42_escape.playing] run function animated_java:twins_rubiel/animations/42_escape/zzz/on_tick
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:twins_rubiel/as_root/post_tick