# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.convict.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'convict', 'function_path': 'animated_java:convict/animations/summon/apply_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.summon.frame $(frame)
execute at @s run function animated_java:convict/animations/summon/zzz/apply_frame with storage aj:temp