# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.behemoth_aj.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'behemoth_aj', 'function_path': 'animated_java:behemoth_aj/animations/5_flatten5/apply_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.5_flatten5.frame $(frame)
execute at @s run function animated_java:behemoth_aj/animations/5_flatten5/zzz/apply_frame with storage aj:temp