# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tultaria.root] run return 0
execute on passengers if entity @s[tag=aj.tultaria.data] unless data entity @s {data:{rigHash: '5fcf7bd64edf155e85428faedc8e411da22c130fce79109ff085bab764f348d1'}} on vehicle run function animated_java:tultaria/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1