# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers run data modify entity @s[tag=aj.heiloang_flare_aj.bone.background4] {} merge from storage aj.heiloang_flare_aj:animations spin.$(frame).bone_background4
execute on passengers run data modify entity @s[type=!marker] start_interpolation set value -1