# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.louvert.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:louvert/as_root/pre_tick
execute if entity @s[tag=aj.louvert.animation.15_4_final_spell_fire.playing] run function animated_java:louvert/animations/15_4_final_spell_fire/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.15_3_final_spell_iai_finish.playing] run function animated_java:louvert/animations/15_3_final_spell_iai_finish/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.15_2_final_spell_iai_start.playing] run function animated_java:louvert/animations/15_2_final_spell_iai_start/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.15_1_final_spell.playing] run function animated_java:louvert/animations/15_1_final_spell/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.14_1_falling_strike.playing] run function animated_java:louvert/animations/14_1_falling_strike/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.13_1_ending.playing] run function animated_java:louvert/animations/13_1_ending/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.12_1_opening.playing] run function animated_java:louvert/animations/12_1_opening/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.11_1_cast_magic.playing] run function animated_java:louvert/animations/11_1_cast_magic/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.10_1_counter.playing] run function animated_java:louvert/animations/10_1_counter/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.09_2_triple_slash_slash.playing] run function animated_java:louvert/animations/09_2_triple_slash_slash/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.09_1_triple_slash_start.playing] run function animated_java:louvert/animations/09_1_triple_slash_start/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.07_1_soul_magic_cast.playing] run function animated_java:louvert/animations/07_1_soul_magic_cast/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.06_4_move_attack.playing] run function animated_java:louvert/animations/06_4_move_attack/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.06_3_move_stop.playing] run function animated_java:louvert/animations/06_3_move_stop/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.06_2_moving.playing] run function animated_java:louvert/animations/06_2_moving/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.06_1_move_start.playing] run function animated_java:louvert/animations/06_1_move_start/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.05_1_blade_cutter.playing] run function animated_java:louvert/animations/05_1_blade_cutter/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.04_1_flame_magic_cast.playing] run function animated_java:louvert/animations/04_1_flame_magic_cast/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.03_2_fire_slash_slash_1.playing] run function animated_java:louvert/animations/03_2_fire_slash_slash_1/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.03_1_fire_slash_charge_1.playing] run function animated_java:louvert/animations/03_1_fire_slash_charge_1/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.02_2_damage.playing] run function animated_java:louvert/animations/02_2_damage/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.02_1_damage.playing] run function animated_java:louvert/animations/02_1_damage/zzz/on_tick
execute if entity @s[tag=aj.louvert.animation.01_idle.playing] run function animated_java:louvert/animations/01_idle/zzz/on_tick
execute on passengers if entity @s[tag=aj.louvert.data] run function animated_java:louvert/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:louvert/as_root/post_tick