# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gem_attack_drone.root] run return 0
execute on passengers if entity @s[tag=aj.gem_attack_drone.data] unless data entity @s {data:{rigHash: 'ee35a3061d896c4b1851c5a5a40ccb389b139d2e2e4db6d9baac47b71ea43406'}} on vehicle run function animated_java:gem_attack_drone/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1