# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gargo_ex_machina/root/zzz/2 with entity @s data.locators.hitbox_2
function animated_java:gargo_ex_machina/root/zzz/4 with entity @s data.locators.hitbox_3
function animated_java:gargo_ex_machina/root/zzz/6 with entity @s data.locators.hitbox_1
function animated_java:gargo_ex_machina/root/zzz/8 with entity @s data.locators.hitbox_0
function animated_java:gargo_ex_machina/root/zzz/10 with entity @s data.locators.hitbox_right_0
function animated_java:gargo_ex_machina/root/zzz/12 with entity @s data.locators.hitbox_right_1
function animated_java:gargo_ex_machina/root/zzz/14 with entity @s data.locators.hitbox_right_2
function animated_java:gargo_ex_machina/root/zzz/16 with entity @s data.locators.hitbox_left_3
function animated_java:gargo_ex_machina/root/zzz/18 with entity @s data.locators.hitbox_left_4
function animated_java:gargo_ex_machina/root/zzz/20 with entity @s data.locators.hitbox_left_5