# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.twins_sapphiel.root] run return 0
execute on passengers if entity @s[tag=aj.twins_sapphiel.data] unless data entity @s {data:{rigHash: 'e426f83a3e2e3e31be567152c72ce1117a3b33bbae67ebe26a2fd36e8710ea3f'}} on vehicle run function animated_java:twins_sapphiel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1