# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.heiloang_aj.root] run return 0
execute on passengers if entity @s[tag=aj.heiloang_aj.data] unless data entity @s {data:{rigHash: '10e8505b00a1a1dba6c6f25056334dd4759f8ae7f10b73dd813244c22e157e0a'}} on vehicle run function animated_java:heiloang_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1