# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.node.head3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).3
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.node.arm_right3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).4
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.node.arm_left3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).5
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.node.body3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).2
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.node.tail_6] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).7
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.node.tail_5] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).6
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.node.root3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).1
$execute on passengers if entity @s[tag=aj.global.data] run data modify entity @s data.locators.pos merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).l_8