# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.bone.head3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).bone_head3
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.bone.arm_right3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).bone_arm_right3
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.bone.arm_left3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).bone_arm_left3
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.bone.body3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).bone_body3
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.bone.tail_6] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).bone_tail_6
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.bone.tail_5] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).bone_tail_5
$execute on passengers if entity @s[tag=aj.ic_pisce_aj.bone.root3] run data modify entity @s {} merge from storage aj.ic_pisce_aj:animations 0_start.$(frame).bone_root3