# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.karmic.node.head] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_head
$execute on passengers if entity @s[tag=aj.karmic.node.rightscythe_handle] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_rightscythe_handle
$execute on passengers if entity @s[tag=aj.karmic.node.sword] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_sword
$execute on passengers if entity @s[tag=aj.karmic.node.righthand] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_righthand
$execute on passengers if entity @s[tag=aj.karmic.node.rightarm] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_rightarm
$execute on passengers if entity @s[tag=aj.karmic.node.gun] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_gun
$execute on passengers if entity @s[tag=aj.karmic.node.leftscythe_handle] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_leftscythe_handle
$execute on passengers if entity @s[tag=aj.karmic.node.lefthand] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_lefthand
$execute on passengers if entity @s[tag=aj.karmic.node.leftarm] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_leftarm
$execute on passengers if entity @s[tag=aj.karmic.node.body] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_body
$execute on passengers if entity @s[tag=aj.karmic.node.leftfeet] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_leftfeet
$execute on passengers if entity @s[tag=aj.karmic.node.leftleg] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_leftleg
$execute on passengers if entity @s[tag=aj.karmic.node.rightfeet] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_rightfeet
$execute on passengers if entity @s[tag=aj.karmic.node.rightleg] run data modify entity @s {} merge from storage aj.karmic:animations run_end_slash2_unused.$(frame).bone_rightleg