# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_0']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/2
data modify entity @s data.locators.hitbox_head_0.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_1']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/3
data modify entity @s data.locators.hitbox_head_1.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_2']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/4
data modify entity @s data.locators.hitbox_head_2.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_3']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/5
data modify entity @s data.locators.hitbox_head_3.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_7']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/6
data modify entity @s data.locators.hitbox_head_7.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_6']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/7
data modify entity @s data.locators.hitbox_head_6.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_5']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/8
data modify entity @s data.locators.hitbox_head_5.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_4']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/9
data modify entity @s data.locators.hitbox_head_4.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_8']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/10
data modify entity @s data.locators.hitbox_head_8.uuid set from storage aj:uuid main.out
summon minecraft:slime ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.heiloang_aj.locator', 'aj.heiloang_aj.locator.hitbox_head_9']}
execute as @e[type=minecraft:slime,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:heiloang_aj/zzz/11
data modify entity @s data.locators.hitbox_head_9.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.flame_model] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flame_model set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.head_lower] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head_lower set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.horne_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_horne_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.horne_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_horne_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.head_upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head_upper set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.neck_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.neck_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.neck_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.neck_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_neck_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.wing_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.wing_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.wing_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.wing_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.wing_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.wing_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.kazari_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_kazari_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.kazari_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_kazari_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.ring] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ring set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.body_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.leg_right_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.leg_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.leg_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.leg_right_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.leg_left_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.leg_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.leg_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.leg_left_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.tail_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.tail_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.tail_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.tail_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.tail_ring] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_ring set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.tail_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.heiloang_aj.bone.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out