# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.eclael.root] run return 0
execute on passengers if entity @s[tag=aj.eclael.data] unless data entity @s {data:{rigHash: '6c65a6339095b893ade2229d6d0b10ea4a86581f356b011f3df126129c431f1b'}} on vehicle run function animated_java:eclael/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1