# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.behemoth_aj.root] run return 0
execute on passengers if entity @s[tag=aj.behemoth_aj.data] unless data entity @s {data:{rigHash: '88d00318ee4ed9334345c88f524c0568934fe0a7940c088a1ecad70cfbbd2846'}} on vehicle run function animated_java:behemoth_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1