# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.behemoth_aj.root] run return 0
execute on passengers if entity @s[tag=aj.behemoth_aj.data] unless data entity @s {data:{rigHash: '89d50c970c875e01702b73c05cae6c92c5fb487268cf9a67e73e45c31287f891'}} on vehicle run function animated_java:behemoth_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1