# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.behemoth_aj.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:behemoth_aj/as_root/pre_tick
execute if entity @s[tag=aj.behemoth_aj.animation.pose.playing] run function animated_java:behemoth_aj/animations/pose/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.1_idle.playing] run function animated_java:behemoth_aj/animations/1_idle/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.2_move.playing] run function animated_java:behemoth_aj/animations/2_move/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.3_0_cast_start.playing] run function animated_java:behemoth_aj/animations/3_0_cast_start/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.3_1_casting.playing] run function animated_java:behemoth_aj/animations/3_1_casting/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.4_breath.playing] run function animated_java:behemoth_aj/animations/4_breath/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.5_flatten.playing] run function animated_java:behemoth_aj/animations/5_flatten/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.5_flatten8.playing] run function animated_java:behemoth_aj/animations/5_flatten8/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.5_flatten7.playing] run function animated_java:behemoth_aj/animations/5_flatten7/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.5_flatten6.playing] run function animated_java:behemoth_aj/animations/5_flatten6/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.5_flatten5.playing] run function animated_java:behemoth_aj/animations/5_flatten5/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.5_flatten4.playing] run function animated_java:behemoth_aj/animations/5_flatten4/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.5_flatten3.playing] run function animated_java:behemoth_aj/animations/5_flatten3/zzz/on_tick
execute if entity @s[tag=aj.behemoth_aj.animation.5_flatten2.playing] run function animated_java:behemoth_aj/animations/5_flatten2/zzz/on_tick
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:behemoth_aj/as_root/post_tick