# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.labyria.root] run return 0
execute on passengers if entity @s[tag=aj.labyria.data] unless data entity @s {data:{rigHash: '2987bb9d61bd4123da2a8941bbafcbce3906562b22dda563b2f3e1b4cec9d986'}} on vehicle run function animated_java:labyria/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1