# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.behemoth_aj.root] run return 0
execute on passengers if entity @s[tag=aj.behemoth_aj.data] unless data entity @s {data:{rigHash: '68e415c61e5f503999210ccb4f2d50d74940edcc76e863d4f122626b283e10ea'}} on vehicle run function animated_java:behemoth_aj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1