# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.twins_rubiel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'twins_rubiel', 'function_path': 'animated_java:twins_rubiel/animations/2_0_0_idle_katana_normal/stop'}
tag @s remove aj.twins_rubiel.animation.2_0_0_idle_katana_normal.playing
scoreboard players set @s aj.2_0_0_idle_katana_normal.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:twins_rubiel/animations/2_0_0_idle_katana_normal/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only